feat: Add alerts on huge AAVE and Maker vaults changes
lidofinance/alerting-forta pull request #129
Opened 2022-07-27 17:28 UTC by dgusakov

2022-07-27 17:51 UTC, madlabman requested changes

2022-07-27 17:51 UTC, madlabman commented on ethereum-huge-tx/src/agent-huge-tx.ts
> +  return ((before - after) / before) * 100;
Looks like logic is inverted, because increase will return negative value.
Also it is scaled as a percent, but `balanceChangeThreshold` is `0..1` based so the conditions below won't be triggered.

2022-07-28 06:09 UTC, dgusakov commented on ethereum-huge-tx/src/agent-huge-tx.ts
> +  return ((before - after) / before) * 100;
Fixed

2022-07-28 06:27 UTC, madlabman approved these changes

2022-07-28 06:45 UTC, merged