Add pools balances alerting
lidofinance/alerting-forta pull request #13
Opened 2022-02-18 15:02 UTC by dgusakov

Currently for Curve and Balancer. There are 3 types of alerts:
- Significant pool size change compared to the previous block (XXX_POOL_SIZE_CHANGE)
- Significant pool imbalance (XXX_POOL_IMBALANCE). There is a 1 week silence period after the alert to avoid spamming. Also, if we already have an imbalance on agent start, we will not produce an alert for the next week just in case we suppose that the corresponding alert was already produced earlier. We need it to avoid spamming in case of frequent agent restarts.
- Significant pool imbalance change (XXX_POOL_IMBALANCE_RAPID_CHANGE). No silence period here. After being fired reference value of the reported imbalance is updated and the silence period for XXX_POOL_IMBALANCE is updated back to 1 week

2022-02-22 06:15 UTC, dgusakov commented
Do not merge before https://github.com/lidofinance/alerting-forta/pull/12

2022-02-24 10:16 UTC, skhomuti requested changes

2022-02-24 10:23 UTC, dgusakov commented on src/agent-pools-balances.ts
> +  // get initial Balancer Poll size
Fixed

2022-02-24 10:45 UTC, skhomuti approved these changes

2022-02-24 10:45 UTC, vgorkavenko approved these changes

2022-02-24 10:46 UTC, merged