Lido on polygon
lidofinance/alerting-forta pull request #179
Opened 2022-10-17 15:04 UTC by madlabman

2022-10-25 15:05 UTC, skhomuti submitted a review, later dismissed

2022-10-25 15:12 UTC, dgusakov requested changes

2022-10-25 15:12 UTC, dgusakov commented on .github/workflows/_tests.yml
> +      - name: Check if test:e2e script is presented
```suggestion
      - name: Check if test:e2e script is present
```

2022-10-25 15:16 UTC, madlabman commented on lido-on-polygon/src/agent-dao-ops.ts
> +};
Because of internals of SDK. If we wish to use the agent directly we have to have an export like this.

2022-10-25 15:17 UTC, madlabman commented on lido-on-polygon/e2e/__snapshots__/agent-dao-ops.e2e-spec.ts.snap
> +old reward: 50739",
Nope, it's exact text produced by the agent.

2022-10-25 15:21 UTC, madlabman commented on lido-on-polygon/src/agent-dao-ops.ts
> +        `hours passed since last stMATIC rewards distribution. NOTE: Last rewards distribution event was not found. Usually it means than there is a huge delay in rewards distribution!`;
Fixed

2022-10-25 15:21 UTC, madlabman commented on .github/workflows/_tests.yml
> +      - name: Check if test:e2e script is presented
Fixed

2022-10-26 07:06 UTC, dgusakov approved these changes

2022-10-26 12:05 UTC, merged