Add a separate polygon agent
lidofinance/alerting-forta pull request #27
Opened 2022-03-10 12:58 UTC by dgusakov

2022-03-10 13:45 UTC, madlabman requested changes

2022-03-10 13:45 UTC, madlabman commented on polygon/src/agent-dao-ops.ts
> +          name: "Huge buffered ETH amount",
```suggestion
          name: "Huge buffered MATIC amount",
```

2022-03-10 13:45 UTC, madlabman commented on polygon/src/agent-dao-ops.ts
> +          )} (more that ${MAX_BUFFERED_MATIC_IMMEDIATE_PERCENT}% of total pooled MATIC) buffered MATIC in stMATIC contract`,
```suggestion
          )} (more than ${MAX_BUFFERED_MATIC_IMMEDIATE_PERCENT}% of total pooled MATIC) buffered MATIC in stMATIC contract`,
```

2022-03-10 13:45 UTC, madlabman commented on polygon/src/agent-dao-ops.ts
> +          name: "High buffered ETH amount",
```suggestion
          name: "High buffered MATIC amount",
```

2022-03-10 13:45 UTC, madlabman commented on polygon/src/agent-dao-ops.ts
> +          )} (more that ${MAX_BUFFERED_MATIC_DAILY_PERCENT}% of total pooled MATIC) buffered MATIC in stMATIC contract for more than ${Math.floor(
```suggestion
          )} (more than ${MAX_BUFFERED_MATIC_DAILY_PERCENT}% of total pooled MATIC) buffered MATIC in stMATIC contract for more than ${Math.floor(
```

2022-03-10 13:50 UTC, dgusakov commented on polygon/src/agent-dao-ops.ts
> +          name: "Huge buffered ETH amount",
Fixed

2022-03-10 13:50 UTC, dgusakov commented on polygon/src/agent-dao-ops.ts
> +          )} (more that ${MAX_BUFFERED_MATIC_IMMEDIATE_PERCENT}% of total pooled MATIC) buffered MATIC in stMATIC contract`,
Fixed

2022-03-10 13:50 UTC, dgusakov commented on polygon/src/agent-dao-ops.ts
> +          name: "High buffered ETH amount",
Fixed

2022-03-10 13:50 UTC, dgusakov commented on polygon/src/agent-dao-ops.ts
> +          )} (more that ${MAX_BUFFERED_MATIC_DAILY_PERCENT}% of total pooled MATIC) buffered MATIC in stMATIC contract for more than ${Math.floor(
Fixed

2022-03-10 16:18 UTC, vgorkavenko commented on polygon/src/agent-dao-ops.ts
> +}
Why is `currentBlock` here? Maybe it should also be output?

2022-03-10 16:49 UTC, vgorkavenko approved these changes

2022-03-11 07:53 UTC, dgusakov commented on polygon/src/agent-dao-ops.ts
> +}
Nope. initialize can be more complicated and include multiple rpc calls

2022-03-11 07:55 UTC, merged