feat: staking router subagent
lidofinance/alerting-forta pull request #271
Opened 2023-04-18 13:17 UTC by vgorkavenko

2023-04-20 07:26 UTC, madlabman requested changes

2023-04-24 06:47 UTC, dgusakov commented on ethereum-operations/src/subagents/staking-router/constants.ts
> +    name: "🚨 Staking Router: rewards minting was failed",
Copy paste

2023-04-24 07:00 UTC, vgorkavenko commented on ethereum-operations/src/subagents/staking-router/constants.ts
> +    name: "🚨 Staking Router: rewards minting was failed",
fixed

2023-04-24 08:41 UTC, dgusakov commented on ethereum-operations/src/common/utils.ts
> +  return `https://etherscan.io/address/${address}`;
```suggestion
  return `[${address}](https://etherscan.io/address/${address})`;
```

2023-04-24 09:46 UTC, dgusakov approved these changes

2023-04-24 09:46 UTC, merged