Feat/lido v2 rc
lidofinance/alerting-forta pull request #272
Opened 2023-04-20 07:12 UTC by vgorkavenko

2023-05-09 12:31 UTC, vgorkavenko commented on ethereum-operations/src/subagents/accounting-oracle/constants.ts
> +    name: "ℹ️ Accounting Oracle: Consensus Version Set",
fixed

2023-05-09 12:32 UTC, vgorkavenko commented on ethereum-operations/e2e/agent-dao-ops.e2e-spec.ts
> +  // );
done

2023-05-09 12:32 UTC, vgorkavenko commented on ethereum-operations/e2e/agent-dao-ops.e2e-spec.ts
> +  // );
done

2023-05-09 12:32 UTC, vgorkavenko commented on ethereum-operations/e2e/__snapshots__/agent-lido-report.e2e-spec.ts.snap
> +exports[`agent-lido-report e2e tests should process tx with decreased Lido Beacon rewards 1`] = `undefined`;
done

2023-05-10 07:45 UTC, madlabman commented on ethereum-operations/src/common/constants.testnet.ts
> +  "0x55032650b14df07b85bf18a3a3ec8e0af2e028d5";
```suggestion
  "0x9D4AF1Ee19Dad8857db3a45B0374c81c8A1C6320";
```

2023-05-10 07:45 UTC, madlabman commented on ethereum-operations/src/common/constants.testnet.ts
> +export const EASY_TRACK_ADDRESS = "0xf0211b7660680b49de1a7e9f25c65660f0a13fea";
```suggestion
export const EASY_TRACK_ADDRESS = "0xAf072C8D368E4DD4A9d4fF6A76693887d6ae92Af";
```

2023-05-10 07:52 UTC, madlabman commented on ethereum-operations/src/subagents/accounting-oracle/agent-accounting-hash-consensus.ts
> +  if (txEvent.to === ACCOUNTING_HASH_CONSENSUS_ADDRESS) {
Shall we change to check for address including for sure?

2023-05-10 08:18 UTC, madlabman commented on ethereum-operations/src/subagents/aragon-voting/constants.ts
> +export const FIVE_DAYS_BLOCKS = Math.floor((ONE_HOUR * 24 * 5) / 13);
```suggestion
export const FIVE_DAYS_BLOCKS = Math.floor((ONE_HOUR * 24 * 5) / 12);
```

2023-05-10 08:19 UTC, madlabman commented on ethereum-operations/src/subagents/dao-ops/agent-dao-ops.ts
> +import LIDO_DAO_ABI from "../../abi/Lido.json";
It looks controversial since Lido is a different contract.

2023-05-10 08:22 UTC, madlabman commented on ethereum-operations/src/subagents/dao-ops/constants.ts
>  export const LIDO_DAO_ADDRESS = "0xae7ab96520de3a18e5e111b5eaab095312d7fe84";
It's not a DAO. It points to Lido's (aka stETH) address.

2023-05-10 08:40 UTC, madlabman commented on ethereum-operations/src/subagents/exitbus-oracle/constants.ts
> +export const EL_REWARDS_VAULT_ADDRESS = "";
Why empty?

2023-05-10 15:18 UTC, madlabman commented on ethereum-operations/src/subagents/lido-report/agent-lido-report.ts
> +            .toFixed(3)} ETH`,
I'm not sure that ETH representation is applicable here.

2023-05-10 15:37 UTC, vgorkavenko commented on ethereum-operations/src/subagents/accounting-oracle/agent-accounting-hash-consensus.ts
> +  handleEventsOfNotice(
because `handleEventsOfNotice` already has condition `address in txEvent.addresses`

2023-05-10 15:52 UTC, vgorkavenko commented on ethereum-operations/src/subagents/lido-report/agent-lido-report.ts
> +            .toFixed(3)} ETH`,
What do you suggest? We could remove `ETH`

2023-05-10 15:53 UTC, vgorkavenko commented on ethereum-operations/src/common/constants.testnet.ts
> +  "0x55032650b14df07b85bf18a3a3ec8e0af2e028d5";
fixed

2023-05-10 15:53 UTC, vgorkavenko commented on ethereum-operations/src/common/constants.testnet.ts
> +export const EASY_TRACK_ADDRESS = "0xf0211b7660680b49de1a7e9f25c65660f0a13fea";
fixed

2023-05-10 15:53 UTC, vgorkavenko commented on ethereum-operations/src/subagents/accounting-oracle/agent-accounting-hash-consensus.ts
> +  if (txEvent.to === ACCOUNTING_HASH_CONSENSUS_ADDRESS) {
fixed

2023-05-10 15:53 UTC, vgorkavenko commented on ethereum-operations/src/subagents/exitbus-oracle/constants.ts
> +export const EL_REWARDS_VAULT_ADDRESS = "";
fixed

2023-05-10 15:55 UTC, dgusakov requested changes

2023-05-10 15:55 UTC, dgusakov commented on ethereum-operations/src/subagents/oracle-daemon-config/constants.ts
> +    description: (args: any) => `${args.key}: ${new BigNumber(args.value)}`,
Does value always number?

2023-05-10 15:55 UTC, dgusakov commented on ethereum-operations/src/subagents/proxy-watcher/agent-proxy-watcher.ts
> +    `Proxy contract ${address} does not have implementation function`
```suggestion
    `Proxy contract ${address} does not have "implementation" or "proxy__getImplementation" functions`
```

2023-05-10 15:55 UTC, dgusakov commented on ethereum-operations/src/subagents/sanity-checker/agent-sanity-checker.ts
> +        name: "⚠️ Oracle Report Sanity Checker: some limits were changed",
```suggestion
        name: "⚠️ Oracle Report Sanity Checker: limits were changed",
```

2023-05-10 15:55 UTC, dgusakov commented on ethereum-operations/src/subagents/sanity-checker/agent-sanity-checker.ts
> +        severity: FindingSeverity.Medium,
```suggestion
        severity: FindingSeverity.High,
```

2023-05-10 15:55 UTC, dgusakov commented on ethereum-operations/src/subagents/staking-router/constants.ts
> +    name: "🚨 Staking Router: exited and stuck validators counts update was failed",
```suggestion
    name: "🚨 Staking Router: exited and stuck validators counts update failed",
```

2023-05-10 15:55 UTC, dgusakov commented on ethereum-operations/src/subagents/staking-router/constants.ts
> +    name: "🚨 Staking Router: rewards minting was failed",
```suggestion
    name: "🚨 Staking Router: rewards minting failed",
```

2023-05-10 15:55 UTC, dgusakov commented on ethereum-operations/src/subagents/staking-router/constants.ts
> +        args.stakingModule
```suggestion
        etherscanAddress(args.stakingModule)
```

2023-05-10 15:55 UTC, dgusakov commented on ethereum-operations/src/subagents/withdrawals/agent-withdrawals.ts
> +  }
Unused later

2023-05-10 15:55 UTC, dgusakov commented on ethereum-operations/src/subagents/withdrawals/constants.ts
> +    name: "ℹ️ Withdrawals: contract was unpaused",
```suggestion
    name: "✅ Withdrawals: contract was unpaused",
```

2023-05-10 15:55 UTC, dgusakov commented on ethereum-operations/src/subagents_v1/dao-ops/agent-dao-ops.ts
> +const MEV_RELAY_COUNT_REPORT_WINDOW = 60 * 60 * 24;
Move to consts

2023-05-10 15:55 UTC, dgusakov commented on ethereum-operations/src/subagents_v1/easy-track/agent-easy-track.ts
> +        let alertName = "ℹ EasyTrack: New motion created";
```suggestion
        let alertName = "ℹ️ EasyTrack: New motion created";
```

2023-05-10 16:04 UTC, vgorkavenko commented on ethereum-operations/src/subagents/accounting-oracle/agent-accounting-hash-consensus.ts
> +  if (txEvent.to === ACCOUNTING_HASH_CONSENSUS_ADDRESS) {
fixed

2023-05-10 16:04 UTC, vgorkavenko commented on ethereum-operations/src/subagents/accounting-oracle/constants.ts
> +export const TRIGGER_PERIOD = 60 * 5;
fixed

2023-05-10 16:05 UTC, vgorkavenko commented on ethereum-operations/src/subagents/accounting-oracle/constants.testnet.ts
> +export const MAX_ORACLE_REPORT_SUBMIT_DELAY = ONE_DAY + 15 * 60; // 24h 15m
fixed

2023-05-10 16:07 UTC, vgorkavenko commented on ethereum-operations/src/subagents/accounting-oracle/constants.ts
> +    severity: FindingSeverity.High,
fixed

2023-05-10 16:08 UTC, vgorkavenko commented on ethereum-operations/src/subagents/accounting-oracle/constants.ts
> +    severity: FindingSeverity.High,
Fixed

2023-05-10 16:09 UTC, vgorkavenko commented on ethereum-operations/src/subagents/accounting-oracle/constants.ts
> +    severity: FindingSeverity.High,
fixed

2023-05-10 16:09 UTC, vgorkavenko commented on ethereum-operations/src/subagents/exitbus-oracle/agent-exitbus-hash-consensus.ts
> +  if (txEvent.to === EXITBUS_HASH_CONSENSUS_ADDRESS) {
fixed

2023-05-10 16:10 UTC, vgorkavenko commented on ethereum-operations/src/subagents/exitbus-oracle/constants.testnet.ts
> +export const MAX_ORACLE_REPORT_SUBMIT_DELAY = 8 * ONE_HOUR + 15 * 60; // 8h 15m
fixed

2023-05-10 16:10 UTC, vgorkavenko commented on ethereum-operations/src/subagents/exitbus-oracle/constants.ts
> +export const TRIGGER_PERIOD = 60 * 5;
fixed

2023-05-10 16:19 UTC, vgorkavenko commented on ethereum-operations/src/subagents/exitbus-oracle/constants.ts
> +    severity: FindingSeverity.High,
fixed

2023-05-10 16:19 UTC, vgorkavenko commented on ethereum-operations/src/subagents/exitbus-oracle/constants.ts
> +    severity: FindingSeverity.High,
fixed

2023-05-10 16:19 UTC, vgorkavenko commented on ethereum-operations/src/subagents/exitbus-oracle/constants.ts
> +    severity: FindingSeverity.High,
fixed

2023-05-10 16:19 UTC, vgorkavenko commented on ethereum-operations/src/subagents/exitbus-oracle/constants.ts
> +    severity: FindingSeverity.High,
fixed

2023-05-10 16:20 UTC, vgorkavenko commented on ethereum-operations/src/subagents/exitbus-oracle/constants.ts
> +    severity: FindingSeverity.High,
fixed

2023-05-10 16:21 UTC, vgorkavenko commented on ethereum-operations/src/subagents/lido-report/agent-lido-report.ts
> +  }
removed

2023-05-10 16:23 UTC, vgorkavenko commented on ethereum-operations/src/subagents/lido-report/agent-lido-report.ts
> +          name: `⚠️ ELRewardsVault overfilled: balance more than ${OVERFILL_THRESHOLD_PERCENT}% of TVL`,
fixed

2023-05-10 16:23 UTC, vgorkavenko commented on ethereum-operations/src/subagents/lido-report/agent-lido-report.ts
> +          name: `⚠️ ELRewardsVault overfilled: balance more than ${OVERFILL_THRESHOLD_PERCENT}% of TVL`,
fixed

2023-05-10 16:23 UTC, vgorkavenko commented on ethereum-operations/src/subagents/lido-report/agent-lido-report.ts
> +          name: `⚠️ WithdrawalsVault overfilled: balance more than ${OVERFILL_THRESHOLD_PERCENT}% of TVL`,
fixed

2023-05-10 16:24 UTC, vgorkavenko commented on ethereum-operations/src/subagents/lido-report/agent-lido-report.ts
> +          name: `⚠️ Burner overfilled: unburnt shares more than ${OVERFILL_THRESHOLD_PERCENT}% of total shares`,
fixed

2023-05-10 16:25 UTC, vgorkavenko commented on ethereum-operations/src/subagents/lido-report/agent-lido-report.ts
> +    }, Shares: ${shares.toFixed(3)} ETH, Ether: ${ether.toFixed(3)} ETH`;
fixed

2023-05-10 16:25 UTC, vgorkavenko commented on ethereum-operations/src/subagents/lido-report/agent-lido-report.ts
> +    }, Shares: ${shares.toFixed(3)} ETH, Ether: ${ether.toFixed(3)} ETH`;
fixed

2023-05-10 16:27 UTC, vgorkavenko commented on ethereum-operations/src/subagents/node-operators-registry/agent-node-operators-registry.ts
> +          description: `ID: ${nodeOperatorId}\nNew exited: ${newExited}`,
fixed

2023-05-10 16:27 UTC, vgorkavenko commented on ethereum-operations/src/subagents/node-operators-registry/agent-node-operators-registry.ts
> +            description: `ID: ${nodeOperatorId}\nStuck exited: ${lastDigest.stuck}`,
fixed

2023-05-10 16:28 UTC, vgorkavenko commented on ethereum-operations/src/subagents/node-operators-registry/agent-node-operators-registry.ts
> +            description: `ID: ${nodeOperatorId}\nNew stuck: ${stuckValidatorsCount}`,
fixed

2023-05-10 16:28 UTC, vgorkavenko commented on ethereum-operations/src/subagents/node-operators-registry/agent-node-operators-registry.ts
> +            description: `ID: ${nodeOperatorId}\nNew stuck: ${stuckValidatorsCount}`,
fixed

2023-05-10 16:28 UTC, vgorkavenko commented on ethereum-operations/src/subagents/node-operators-registry/agent-node-operators-registry.ts
> +            description: `ID: ${nodeOperatorId}\nRefunded: ${refundedValidatorsCount}`,
fixed

2023-05-10 16:28 UTC, vgorkavenko commented on ethereum-operations/src/subagents/node-operators-registry/constants.ts
> +export const NODE_OPERATOR_NEW_STUCK_KEYS_THRESHOLD = 10;
fixed

2023-05-10 16:29 UTC, vgorkavenko commented on ethereum-operations/src/subagents/oracle-daemon-config/constants.ts
> +    description: (args: any) => `${args.key}: ${new BigNumber(args.value)}`,
fixed

2023-05-10 16:31 UTC, vgorkavenko commented on ethereum-operations/src/subagents/proxy-watcher/agent-proxy-watcher.ts
> +    `Proxy contract ${address} does not have implementation function`
fixed

2023-05-10 16:32 UTC, vgorkavenko commented on ethereum-operations/src/subagents/staking-router/constants.ts
> +    name: "🚨 Staking Router: exited and stuck validators counts update was failed",
fixed

2023-05-10 16:32 UTC, vgorkavenko commented on ethereum-operations/src/subagents/staking-router/constants.ts
> +    name: "🚨 Staking Router: rewards minting was failed",
fixed

2023-05-10 17:36 UTC, vgorkavenko commented on ethereum-operations/src/subagents_v1/dao-ops/agent-dao-ops.ts
> +const MEV_RELAY_COUNT_REPORT_WINDOW = 60 * 60 * 24;
it's old agent

2023-05-10 17:40 UTC, vgorkavenko commented on ethereum-operations/src/subagents/dao-ops/constants.testnet.ts
> +export const TRP_FACTORY_ADDRESS = "0x8d20fd1ac547e035bf01089cfb92459054f82ff7";
outdated

2023-05-10 17:44 UTC, vgorkavenko commented on ethereum-operations/src/subagents/dao-ops/constants.ts
>  export const LIDO_DAO_ADDRESS = "0xae7ab96520de3a18e5e111b5eaab095312d7fe84";
yep

2023-05-10 17:44 UTC, vgorkavenko commented on ethereum-operations/src/subagents/dao-ops/agent-dao-ops.ts
> +import LIDO_DAO_ABI from "../../abi/Lido.json";
Yep. It's Lido contract. Fixed

2023-05-10 17:53 UTC, madlabman commented on ethereum-operations/src/subagents/dao-ops/agent-dao-ops.ts
> +  const lidoDao = new ethers.Contract(LIDO_ADDRESS, LIDO_ABI, ethersProvider);
So it should be`lido`.

2023-05-10 17:53 UTC, madlabman commented on ethereum-operations/src/subagents/exitbus-oracle/constants.ts
> +  "0xa2ecee311e61edaf4a3ac56b437fddfaced8da80";
```suggestion
  "0x889edC2eDab5f40e902b864aD4d7AdE8E412F9B1";
```

2023-05-10 17:55 UTC, madlabman commented on ethereum-operations/src/subagents/lido-report/agent-lido-report.ts
> +            .toFixed(3)} ETH`,
We should ask the folks, I think. ETH may replaced with `1e18`.

2023-05-10 18:02 UTC, madlabman commented on ethereum-operations/src/subagents/lido-report/constants.ts
> +export const BURNER_ADDRESS = "0xb9d7934878b5fb9610b3fe8a5e441e8fad7e293f";
```suggestion
export const BURNER_ADDRESS = "0xD15a672319Cf0352560eE76d9e89eAB0889046D3";
```

2023-05-10 18:27 UTC, madlabman commented on ethereum-operations/src/subagents/node-operators-registry/constants.ts
> +    event: "event NodeOperatorNameSet(uint256 indexed id, string name)",
```suggestion
    event: "event NodeOperatorNameSet(uint256 indexed nodeOperatorId, string name)",
```

Double-check, please.

2023-05-10 18:27 UTC, madlabman commented on ethereum-operations/src/subagents/node-operators-registry/constants.ts
>        "event NodeOperatorRewardAddressSet(uint256 indexed id, address rewardAddress)",
```suggestion
      "event NodeOperatorRewardAddressSet(uint256 indexed nodeOperatorId, address rewardAddress)",
```

2023-05-10 18:28 UTC, madlabman commented on ethereum-operations/src/subagents/node-operators-registry/constants.ts
>        "event NodeOperatorTotalStoppedValidatorsReported(uint256 indexed id, uint64 totalStopped)",
I didn't find the event.

2023-05-11 06:56 UTC, vgorkavenko commented on ethereum-operations/src/subagents/node-operators-registry/agent-node-operators-registry.ts
> +  // initialize, // sdk won't provide any arguments to the function
It is the same in all sub-agents. It might be changed after v2 (during snapshots update)

2023-05-11 07:27 UTC, vgorkavenko commented on ethereum-operations/src/subagents/node-operators-registry/constants.ts
>        "event NodeOperatorTotalStoppedValidatorsReported(uint256 indexed id, uint64 totalStopped)",
removed

2023-05-11 13:26 UTC, madlabman commented on ethereum-operations/src/subagents/withdrawals/agent-withdrawals.ts
> +        )}% of stake limit is drained and unfinalized queue is on par with drained stake limit`,
What is **on par**?

2023-05-11 15:58 UTC, madlabman commented on ethereum-operations/src/subagents/acl-changes/constants.ts
> +    "0xC77F8768774E1c9244BEed705C4354f2113CFc09",
I added to some point.

2023-05-11 16:02 UTC, vgorkavenko commented on ethereum-operations/src/subagents/withdrawals/agent-withdrawals.ts
> +        )}% of stake limit is drained and unfinalized queue is on par with drained stake limit`,
"On the same level"

2023-05-12 09:51 UTC, vgorkavenko commented on ethereum-operations/src/subagents/withdrawals/agent-withdrawals.ts
> +        )}% of stake limit is drained and unfinalized queue is on par with drained stake limit`,
:)

2023-05-15 06:13 UTC, dgusakov approved these changes

2023-05-15 06:13 UTC, skhomuti approved these changes

2023-05-15 06:15 UTC, madlabman approved these changes

2023-05-15 06:16 UTC, merged