feat: GateSeal
lidofinance/alerting-forta pull request #278
Opened 2023-04-27 16:07 UTC by vgorkavenko

2023-04-27 17:22 UTC, dgusakov requested changes

2023-04-27 17:22 UTC, dgusakov commented on ethereum-operations/src/subagents/gate-seal/agent-gate-seal.ts
> +        name: "⚠️ GateSeal: no one actual found",
So we assume that there should always be at least one GateSeal instance?

2023-04-27 17:22 UTC, dgusakov commented on ethereum-operations/src/subagents/gate-seal/agent-gate-seal.ts
> +  if (createdAddresses.length == 0 || !suitedGateSeal) {
Why not to reuse code here and below?

2023-04-27 17:22 UTC, dgusakov commented on ethereum-operations/src/subagents/gate-seal/agent-gate-seal.ts
> +        description: `Address: ${actualGateSeal}}\nLost for:\n${lostDesc}`,
Text is not clear

2023-04-27 17:22 UTC, dgusakov commented on ethereum-operations/src/subagents/gate-seal/agent-gate-seal.ts
> +        description: `Address: ${actualGateSeal}}`,
```suggestion
        description: `GateSeal address: ${actualGateSeal}}`,
```

2023-04-27 17:22 UTC, dgusakov commented on ethereum-operations/src/subagents/gate-seal/agent-gate-seal.ts
> +          description: `Address: ${actualGateSeal}\nExpiry date ${new Date(
```suggestion
          description: `GateSeal address: ${actualGateSeal}\nExpiry date ${new Date(
```

2023-04-27 17:22 UTC, dgusakov commented on ethereum-operations/src/subagents/gate-seal/agent-gate-seal.ts
> +        severity: FindingSeverity.Critical,
HiGH but not critical, I suppose

2023-04-27 17:22 UTC, dgusakov commented on ethereum-operations/src/subagents/gate-seal/agent-gate-seal.ts
> +    if (!expired) {
If all expired?

2023-04-27 17:22 UTC, dgusakov commented on ethereum-operations/src/subagents/gate-seal/agent-gate-seal.ts
> +      blockNumber - Math.ceil(ONE_YEAR / SECONDS_PER_SLOT),
Forta node will not be able to handle range more than 2 weeks(

2023-05-01 08:06 UTC, dgusakov commented on ethereum-operations/src/subagents/gate-seal/agent-gate-seal.ts
> +        severity: FindingSeverity.Critical,
Is that a critical event? Or critical only when there is no new GateSeal?

2023-05-01 08:06 UTC, dgusakov commented on ethereum-operations/src/subagents/gate-seal/agent-gate-seal.ts
> +          severity: FindingSeverity.Critical,
```suggestion
          severity: FindingSeverity.High,
```

2023-05-01 08:16 UTC, vgorkavenko commented on ethereum-operations/src/subagents/gate-seal/agent-gate-seal.ts
> +        severity: FindingSeverity.Critical,
Yes, it should be critical because we will have no new actual GateSeal at that moment

2023-05-01 09:12 UTC, dgusakov approved these changes

2023-05-01 09:13 UTC, merged