feat: suspicious queue
lidofinance/alerting-forta pull request #280
Opened 2023-05-01 11:07 UTC by vgorkavenko

2023-05-04 06:26 UTC, dgusakov commented on ethereum-operations/src/subagents/withdrawals/agent-withdrawals.ts
> +let lastQueueOnParStakeLimitAlertTimestamp = 0;
What does "Par" in the naming means?

2023-05-04 06:34 UTC, vgorkavenko commented on ethereum-operations/src/subagents/withdrawals/agent-withdrawals.ts
> +let lastQueueOnParStakeLimitAlertTimestamp = 0;
> What does "Par" in the naming means?

'on the same level', I guess. This term is taken from hackmd source

2023-05-04 14:23 UTC, dgusakov requested changes

2023-05-04 14:23 UTC, dgusakov commented on ethereum-operations/src/subagents/withdrawals/agent-withdrawals.ts
> +      Array.from(unclaimedRequests.values()),
Can't find handler that will update unclaimedRequests to include new requests

2023-05-05 10:04 UTC, vgorkavenko commented on ethereum-operations/src/subagents/withdrawals/agent-withdrawals.ts
> +  const totalFinalizedSize = claimedSize.plus(unclaimedSize);
fixed

2023-05-05 10:04 UTC, vgorkavenko commented on ethereum-operations/src/subagents/withdrawals/agent-withdrawals.ts
> +      Array.from(unclaimedRequests.values()),
fixed

2023-05-08 08:58 UTC, dgusakov commented on ethereum-operations/src/subagents/withdrawals/agent-withdrawals.ts
> +    if (!isOutdated && !req.claimed) {
We should keep ALL unclaimed requests and look at the ALL unclaimed to claimed over the last 2 weeks requests

2023-05-08 11:40 UTC, vgorkavenko commented on ethereum-operations/src/subagents/withdrawals/agent-withdrawals.ts
> +    if (!isOutdated && !req.claimed) {
fixed

2023-05-09 06:30 UTC, dgusakov approved these changes

2023-05-09 06:30 UTC, merged