Add new reverted-transactions agent
lidofinance/alerting-forta pull request #313
Opened 2023-05-16 09:02 UTC by skhomuti

2023-05-16 09:09 UTC, dgusakov requested changes

2023-05-16 09:09 UTC, dgusakov commented on reverted-tx-watcher/src/agent-reverted-tx.ts
> +            name: "Reverted tx",
```suggestion
            name: "🤔 Reverted TX detected",
```

2023-05-16 09:09 UTC, dgusakov commented on reverted-tx-watcher/src/agent-reverted-tx.ts
> +              `Reverted tx ${fromSelf ? "from" : "to"} the ${name} contract. ` +
```suggestion
              `Reverted TX ${fromSelf ? "from" : "to"} the ${name} contract. ` +
```

2023-05-16 09:09 UTC, dgusakov commented on reverted-tx-watcher/src/agent-reverted-tx.ts
> +  addresses.push(["EasyTrack", EASY_TRACK_ADDRESS]);
Consider adding other Lido contracts not included in the LidoLocator

2023-05-16 09:10 UTC, madlabman commented on reverted-tx-watcher/src/constants.ts
> +  "0xc1d0b3de6792bf6b4b37eccdcc24e45978cfd2eb"; // should be lowercase
Why lowercased?

2023-05-16 10:06 UTC, skhomuti commented on reverted-tx-watcher/src/constants.ts
> +  "0xc1d0b3de6792bf6b4b37eccdcc24e45978cfd2eb"; // should be lowercase
copypasta from demo bot

2023-05-16 10:07 UTC, skhomuti commented on reverted-tx-watcher/src/agent-reverted-tx.ts
> +  addresses.push(["EasyTrack", EASY_TRACK_ADDRESS]);
wanted to ask you what else contracts needed to be added

2023-05-16 11:14 UTC, dgusakov commented on reverted-tx-watcher/src/agent-reverted-tx.ts
> +  addresses.push(["EasyTrack", EASY_TRACK_ADDRESS]);
All major from the docs IMO

2023-05-17 06:04 UTC, skhomuti commented on reverted-tx-watcher/src/agent-reverted-tx.ts
> +  addresses.push(["EasyTrack", EASY_TRACK_ADDRESS]);
added some

2023-05-17 07:54 UTC, skhomuti commented on reverted-tx-watcher/README.md
> +
added

2023-05-17 07:55 UTC, dgusakov approved these changes

2023-05-17 11:10 UTC, merged