Add Lybra finance alert to constants
lidofinance/alerting-forta pull request #377
Opened 2023-07-13 14:06 UTC by gregshestakovlido

Added new Lybra finance pattern for alerting

2023-07-14 05:28 UTC, skhomuti commented on ethereum-huge-tx/src/subagents/huge-tx/constants.ts
> +      `were supplied to  Lybra Finance\n` +
```suggestion
      `were supplied to Lybra Finance\n` +
```

2023-07-14 06:24 UTC, dgusakov requested changes

2023-07-14 06:24 UTC, dgusakov commented on ethereum-huge-tx/src/subagents/huge-tx/constants.ts
> +      `by: ${info.from} (${info.fromName})`,
```suggestion
      `by: ${info.to} (${info.toName})`,
```

2023-07-24 08:35 UTC, dgusakov submitted a review, later dismissed

2023-07-25 08:30 UTC, dgusakov approved these changes

2023-07-25 08:33 UTC, merged