Operations opt split
lidofinance/alerting-forta pull request #383
Opened 2023-08-04 14:48 UTC by vgorkavenko

2023-08-07 08:25 UTC, madlabman commented on ethereum-validators-set/src/subagents/exitbus-oracle/agent-exitbus-oracle.ts
> +async function updateMaxValidatorExitRequestsPerReport(block: number) {}
Abandoned?

2023-08-07 08:27 UTC, madlabman commented on ethereum-validators-set/src/subagents/node-operators-registry/agent-node-operators-registry.ts
> +  if (blockEvent.blockNumber % BLOCK_INTERVAL == 0) {
🫠

2023-08-07 08:35 UTC, madlabman commented on ethereum-validators-set/src/subagents/sanity-checker/agent-sanity-checker.ts
> +        new BigNumber(String(event.args[limitName]))
```
> new BigNumber(1) != new BigNumber(0)
true
> new BigNumber(1) != new BigNumber(1)
true
>
```

Strings comparison should be enough I think

2023-08-07 10:50 UTC, vgorkavenko commented on ethereum-validators-set/src/subagents/sanity-checker/agent-sanity-checker.ts
> +        new BigNumber(String(event.args[limitName]))
fixed

2023-08-07 10:50 UTC, vgorkavenko commented on ethereum-validators-set/src/subagents/exitbus-oracle/agent-exitbus-oracle.ts
> +async function updateMaxValidatorExitRequestsPerReport(block: number) {}
fixed

2023-08-07 11:19 UTC, madlabman approved these changes

2023-08-07 17:09 UTC, dgusakov requested changes

2023-08-07 17:09 UTC, dgusakov commented on ethereum-governance/package.json
Package naming

2023-08-07 17:09 UTC, dgusakov commented on ethereum-steth/src/subagents/steth-ops/agent-steth-ops.ts
> +    handleStakingLimit(blockEvent, findings), //
```suggestion
    handleStakingLimit(blockEvent, findings),
```

2023-08-07 17:09 UTC, dgusakov commented on ethereum-steth/src/abi/ENS.json
Pls remove unused ABIs from the new agents

2023-08-08 06:47 UTC, vgorkavenko commented on ethereum-steth/e2e/agent-steth-ops.e2e-spec.ts
> +  //  uncomment or remove after V2
removed

2023-08-08 06:47 UTC, vgorkavenko commented on ethereum-steth/package.json
> +  "name": "lido-operations-forta-bot",
fixed

2023-08-08 06:47 UTC, vgorkavenko commented on ethereum-governance/package.json
fixed

2023-08-08 06:48 UTC, vgorkavenko commented on ethereum-steth/src/subagents/steth-ops/agent-steth-ops.ts
> +export const name = "stETHops";
done

2023-08-08 06:48 UTC, vgorkavenko commented on ethereum-steth/src/subagents/steth-ops/agent-steth-ops.ts
> +    handleStakingLimit(blockEvent, findings), //
removed

2023-08-08 06:48 UTC, vgorkavenko commented on ethereum-validators-set/package.json
> +  "name": "lido-operations-forta-bot",
fixed

2023-08-08 06:48 UTC, vgorkavenko commented on ethereum-steth/src/abi/ENS.json
done

2023-08-08 06:56 UTC, dgusakov approved these changes

2023-08-08 15:09 UTC, merged