fix: eth-finacial/pool-balance ADD absolute values in description ale…
lidofinance/alerting-forta pull request #403
Opened 2023-09-26 13:09 UTC by sergeyWh1te

fix: eth-finacial/pool-balance ADD absolute values in description alert section about pool balance size

2023-09-26 14:05 UTC, dgusakov requested changes

2023-09-26 14:05 UTC, dgusakov commented on ethereum-financial/src/subagents/pools-balances/agent-pools-balances.ts
> +        description: `On block(${blockEvent.blockNumber.toString()}) Balancer Pool size has ${
Block info is available in alert metadata. No need to mention it here explicitly

2023-09-26 14:05 UTC, dgusakov commented on ethereum-financial/src/subagents/pools-balances/agent-pools-balances.ts
> +          .toString()}`,
```suggestion
        }% since the last block. Prev: ${prevPoolSize.div(ETH_DECIMALS)
          .toFixed(2)} ETH, Cur: ${curPoolSize.div(ETH_DECIMALS)
          .toFixed(2)} ETH. Diff: ${curPoolSize
          .minus(prevPoolSize).div(ETH_DECIMALS)
          .toFixed(2)}`,
```

2023-09-26 14:11 UTC, sergeyWh1te commented on ethereum-financial/src/subagents/pools-balances/agent-pools-balances.ts
> +        description: `On block(${blockEvent.blockNumber.toString()}) Balancer Pool size has ${
231baf3d4135461d19f5e73ae7598fddfc9d8ed6

2023-09-26 15:17 UTC, dgusakov approved these changes

2023-09-26 15:17 UTC, dgusakov commented on ethereum-financial/src/subagents/pools-balances/agent-pools-balances.ts
> +          .toFixed(2)}`,
```suggestion
          .toFixed(2)} ETH`,
```

2023-09-26 17:04 UTC, arwer13 approved these changes
LGTM, thanks.

2023-09-26 17:04 UTC, arwer13 commented on ethereum-financial/forta.config.example.json
> +  "jsonRpcUrl": "<provide pass to el url>"
Its unclear what is meant by "pass to url", although its not hard to guess. Maybe just "provide JSON RPC url" or something like "put the url here"?

2023-09-27 12:25 UTC, dgusakov approved these changes

2023-09-27 13:18 UTC, arwer13 approved these changes

2023-09-27 13:18 UTC, merged