feat: add l2-bridge-base
lidofinance/alerting-forta pull request #428
Opened 2023-10-25 12:47 UTC by sergeyWh1te

2023-11-01 07:00 UTC, arwer13 requested changes
Thank you, looks fine to me 👍. I've left only a few minor refactor-related comments.

In general I think we should getting out of code duplication: I mean arbitrum, optimism and base and there are more L2s to come. But I propose it to be one of the next iterations.

2023-11-01 09:25 UTC, sergeyWh1te commented on l2-bridge-base/src/agent.ts
> +type CustomHandleBlock = (blockEvent: BlockDto) => Promise<Finding[]>;
dto - it's a common pattern to name objects. Dto (data transfer object)
For example: https://www.okta.com/identity-101/dto/

2023-11-01 09:35 UTC, sergeyWh1te commented on l2-bridge-base/src/agent.ts
> +let cachedBlockDto: BlockDto;
Delegate this question to forta team.

2023-11-01 09:41 UTC, sergeyWh1te commented on l2-bridge-base/src/agent-withdrawals.ts
> +export async function handleTransaction(logs: Log[], blockEvents: BlockDto[]) {
fixed

2023-11-01 10:02 UTC, arwer13 commented on l2-bridge-base/src/agent.ts
> +type CustomHandleBlock = (blockEvent: BlockDto) => Promise<Finding[]>;
Got it

2023-11-01 10:40 UTC, sergeyWh1te commented on l2-bridge-base/src/agent-balance.ts
> +export async function handleBlock(block: BlockDto) {
moved

2023-11-01 12:15 UTC, arwer13 submitted a review, later dismissed
I'm also a little concerned about the lack of tests e.g. like e2e in ethereum-steth agent, but as far as it lacked in optimism, let's consider the tests in the next iteration.

2023-11-01 12:15 UTC, arwer13 commented on l2-bridge-base/src/agent.ts
> +    const blocksInterval = range(cachedBlockDto.number, latestBlock.number);
Fixed

2023-11-02 09:33 UTC, arwer13 approved these changes

2023-11-02 09:39 UTC, arwer13 approved these changes

2023-11-02 10:26 UTC, dgusakov submitted a review, later dismissed

2023-11-02 10:39 UTC, arwer13 approved these changes

2023-11-02 10:40 UTC, dgusakov approved these changes

2023-11-02 10:46 UTC, merged