Improve Lido reverted-tx-watcher bot
lidofinance/alerting-forta pull request #431
Opened 2023-10-28 05:03 UTC by larmork

Low and medium severity alerts added for high gas usage in reverted tx and accordingly for large amount of reverts per day by one EOA

2023-11-03 10:14 UTC, dgusakov requested changes

2023-11-05 21:50 UTC, larmork commented on reverted-tx-watcher/src/agent-reverted-tx.ts
> +  setInterval(resetDictionary, 24 * 60 * 60 * 1000);
Done!

2023-11-05 21:50 UTC, larmork commented on reverted-tx-watcher/src/findings.ts
> +  export const createLowSeverityFinding = (
Fixed

2023-11-05 21:50 UTC, larmork commented on reverted-tx-watcher/src/findings.ts
> +  export const createMediumSeverityFinding = (
Fixed

2023-11-05 21:51 UTC, larmork commented on reverted-tx-watcher/src/findings.ts
> +    };
Already added

2023-11-05 21:53 UTC, larmork commented on reverted-tx-watcher/src/agent-reverted-tx.ts
> +startTimer()
Done

2023-12-11 20:59 UTC, dgusakov approved these changes

2023-12-12 09:13 UTC, sergeyWh1te approved these changes
It'd be great to add eslint + prettier rules for the project.

2023-12-13 11:18 UTC, dgusakov approved these changes

2023-12-13 12:52 UTC, sergeyWh1te approved these changes

2023-12-13 12:53 UTC, merged