L2 bridge zk sync
lidofinance/alerting-forta pull request #432
Opened 2023-11-14 13:08 UTC by sergeyWh1te

2023-11-15 09:16 UTC, TheDZhon reviewed
Could you please provide a description of the PR?

It would be helpful to know: 
- what are the alerts are introduced
- what networks affected
- what is the source for the addresses and constants
- etc

2023-11-15 10:56 UTC, TheDZhon requested changes
:heart:  Thank you for such a significant amount of effort and job done so far.

Left some edits and suggestions, please try not only to fix those for zkSync, but also re-visit the Base and Opti/Arbi cases when applicable.

No rush with zkSync at this moment, so better to be laser-focused.

I am also wondering, if is it possible to implement the test coverage somehow, at least in the future; a bit weird to have those extensive checks without smoke tests.

2023-11-15 10:56 UTC, TheDZhon commented on l2-bridge-zksync/src/constants.ts
> +export const WITHDRAWAL_INITIATED_EVENT =
:warning:  I am afraid, the zkSync bridge contains a slightly different event here: https://github.com/txfusion/lido-l2/blob/main/zksync/l2/contracts/L2ERC20Bridge.sol#L91

Please update the signature and re-visit ABIs as said above

2023-11-15 10:56 UTC, TheDZhon commented on l2-bridge-zksync/src/constants.ts
> +    contractAddress: "0xBD80E505ECC49BAE2cc86094a78fA0e2dB28b52A",
```suggestion
    proxyAdminAddress: "0xBD80E505ECC49BAE2cc86094a78fA0e2dB28b52A",
```

2023-11-15 10:56 UTC, TheDZhon commented on l2-bridge-zksync/src/constants.ts
> +    contractAddress: "0xBD80E505ECC49BAE2cc86094a78fA0e2dB28b52A",
```suggestion
    proxyAdminAddress: "0xBD80E505ECC49BAE2cc86094a78fA0e2dB28b52A",
```

2023-11-15 10:56 UTC, TheDZhon commented on l2-bridge-zksync/src/constants.ts
> +        type: FindingType.Info,
I am afraid it's not applicable to `TransparentUpgradableProxy` (the code was written for `OssifiableProxy`)

2023-11-15 10:56 UTC, TheDZhon commented on l2-bridge-zksync/src/constants.ts
> +        address: proxyInfo.contractAddress,
I suppose the event should be originated from the `proxyAddress` itself

2023-11-15 10:56 UTC, TheDZhon commented on l2-bridge-zksync/src/constants.ts
> +        address: proxyInfo.contractAddress,
the same as above

2023-11-15 10:56 UTC, TheDZhon commented on l2-bridge-zksync/src/constants.ts
> +    const eventsDesc: EventOfNotice[] = [
what we miss here is when the `ProxyAdmin` instance gets a new `owner`
see https://github.com/OpenZeppelin/openzeppelin-contracts/blob/4e17c2e95821b9bff7c2b1e099b078d319142c48/contracts/access/Ownable.sol#L33

2023-11-15 10:56 UTC, TheDZhon commented on l2-bridge-zksync/src/constants.ts
> +        address: proxyInfo.contractAddress,
the same as above

2023-11-15 10:56 UTC, TheDZhon commented on l2-bridge-zksync/src/agent-proxy-watcher.ts
> +
:warning:  one more handler is missing: when the `ProxyAdmin`'s owner is changed

2023-11-15 10:57 UTC, TheDZhon commented
Please consider incorporating #433 here if possible :pray:

2023-11-15 11:22 UTC, sergeyWh1te commented on l2-bridge-zksync/src/agent-proxy-watcher.ts
> +
Here is it:
https://github.com/lidofinance/alerting-forta/pull/432/files#diff-ef12af6d741dc7e50fc8599d3a75d8dce6c974d4ec53a9cc5463b14f7f49a257R200

2023-11-15 11:32 UTC, sergeyWh1te commented on l2-bridge-balance/src/constants.ts
> +    l1Gateway: "0xFf7F4d05e3247374e86A3f7231A2Ed1CA63647F2",
https://github.com/lidofinance/alerting-forta/pull/432/commits/d8615452bf024d9faf973dfc4ddfc8b35ec2bd3a#diff-04cbec0064ab49f4ff91d53359d47e6107a3557304ff4612cc29224b5422a3d2R48

2023-11-15 11:33 UTC, sergeyWh1te commented on l2-bridge-zksync/README.md
https://github.com/lidofinance/alerting-forta/pull/432/commits/d8615452bf024d9faf973dfc4ddfc8b35ec2bd3a#diff-5941ff52eb8a30e21d3b6e2e866e374aeab8513e48d546657013f17a4dfd8f4b

2023-11-15 11:35 UTC, sergeyWh1te commented on l2-bridge-zksync/src/constants.ts
> +    const eventsDesc: EventOfNotice[] = [
https://github.com/lidofinance/alerting-forta/pull/432/commits/d8615452bf024d9faf973dfc4ddfc8b35ec2bd3a#diff-fbeb7f85521f29c3efdbe3838d63bbb892c0e7c2419c8a4db0549a99e0816852R246

2023-11-16 11:34 UTC, sergeyWh1te commented on l2-bridge-zksync/package.json
> +    1
chainId = 1.  Forta does not support zkSync chain yet

2023-11-16 11:36 UTC, sergeyWh1te commented on l2-bridge-zksync/src/constants.ts
> +export const LDO_ADDRESS = "0x5a98fcbea516cf06857215779fd812ca3bef1b32";
removed

2023-11-16 12:13 UTC, TheDZhon requested changes
Thank you, we are getting closer :rocket: 

I would propose to make another round of edits :pray:

2023-11-16 12:13 UTC, TheDZhon commented on l2-bridge-zksync/src/constants.ts
> +        type: FindingType.Info,
`TransparentUpgradableProxy` and its `ProxyAdmin` don't have such an event

2023-11-16 12:13 UTC, TheDZhon commented on l2-bridge-zksync/src/constants.ts
> +        address: proxyInfo.proxyAdminAddress,
```suggestion
        address: proxyInfo.proxyAddress,
```

2023-11-16 12:13 UTC, TheDZhon commented on l2-bridge-zksync/src/constants.ts
> +        address: proxyInfo.proxyAdminAddress,
```suggestion
        address: proxyInfo.proxyAddress,
```

2023-11-16 12:13 UTC, TheDZhon commented on l2-bridge-zksync/src/constants.ts
> +        address: proxyInfo.proxyAdminAddress,
```suggestion
        address: proxyInfo.proxyAddress,
```

2023-11-16 12:13 UTC, TheDZhon commented on l2-bridge-zksync/src/constants.ts
> +        address: proxyInfo.proxyAdminAddress,
:+1: here the address is correct indeed

2023-11-16 12:13 UTC, TheDZhon commented on l2-bridge-zksync/src/constants.ts
> +export const LIDO_PROXY_CONTRACTS: LidoProxy[] = [
> L2ERC20Bridge: [0xE1D6A50E7101c8f8db77352897Ee3f1AC53f782B](https://explorer.zksync.io/address/0xE1D6A50E7101c8f8db77352897Ee3f1AC53f782B) (proxy) 

:warning:  is missing here; however, the contract is `OssifiableProxy`, so the approach should be different :crying_cat_face:

2023-11-16 13:08 UTC, sergeyWh1te commented on l2-bridge-zksync/README.md
> +- Eth mainnet (chain id: 1)
yes, it is

2023-11-16 13:11 UTC, sergeyWh1te commented on l2-bridge-zksync/README.md
> +- ⚠️ ZkSync: Huge withdrawals during the last ...
```ts
`⚠️ ZkSync: Huge withdrawals during the last ` +
                    `${Math.floor(period / (60 * 60))} hour(s)`,
 ```
 
 where period = 
 ```
  const period =
        now - lastReportedToManyWithdrawals < MAX_WITHDRAWALS_WINDOW
            ? now - lastReportedToManyWithdrawals
            : MAX_WITHDRAWALS_WINDOW;
     ```
     
     where MAX_WITHDRAWALS_WINDOW = 48h

2023-11-16 13:58 UTC, sergeyWh1te commented on l2-bridge-zksync/src/constants.ts
> +        type: FindingType.Info,
removed

2023-11-16 14:47 UTC, sergeyWh1te commented on l2-bridge-zksync/src/constants.ts
> +export const LIDO_PROXY_CONTRACTS: LidoProxy[] = [
0a2a7d80af1f47a7f387c9daceda6224fb7d8ec7

2023-11-17 07:29 UTC, TheDZhon requested changes
We are goddamn close :+1:

2023-11-17 07:29 UTC, TheDZhon commented on l2-bridge-zksync/src/agent-proxy-watcher.ts
> +    LIDO_ZKSYNC_PROXY_CONTRACTS.map(async (proxyInfo: LidoZkSyncProxy) => {
I am not sure that it is the best naming to disambiguate `OssifiableProxy` and `TransparentUpgradablyProxy` tbh

maybe just:
`LIDO_TRANSPARENT_PROXY_CONTRACTS` and `LIDO_OSSIFIABLE_PROXY_CONTRACTS`
?

2023-11-17 07:29 UTC, TheDZhon commented on l2-bridge-zksync/src/agent-proxy-watcher.ts
> +async function getZkProxyImpl(proxyInfo: LidoZkSyncProxy, blockNumber: number) {
```suggestion
async function getTransparentUpgradableProxyImpl(proxyInfo: LidoZkSyncProxy, blockNumber: number) {
```

2023-11-17 07:29 UTC, TheDZhon commented on l2-bridge-zksync/src/agent-proxy-watcher.ts
> +async function getProxyImpl(proxyInfo: LidoProxy, blockNumber: number) {
funcs ordering is a bit misleading; maybe group them semantically?

2023-11-17 07:29 UTC, TheDZhon commented on l2-bridge-zksync/src/constants.ts
> +        address: proxyInfo.proxyAdminAddress,
:warning:  I am not sure that the event is emitted from the `ProxyAdmin` contract

2023-11-17 07:29 UTC, TheDZhon commented on l2-bridge-zksync/src/constants.ts
> +        address: proxyInfo.proxyAdminAddress,
:warning:  I am not sure that the event is emitted from the `ProxyAdmin` contract

2023-11-17 07:29 UTC, TheDZhon commented on l2-bridge-zksync/src/constants.ts
> +        address: proxyInfo.proxyAdminAddress,
:warning:  I am not sure that the event is emitted from the `ProxyAdmin` contract

2023-11-17 08:02 UTC, sergeyWh1te commented on l2-bridge-zksync/src/agent-proxy-watcher.ts
> +    LIDO_ZKSYNC_PROXY_CONTRACTS.map(async (proxyInfo: LidoZkSyncProxy) => {
done

2023-11-17 08:02 UTC, sergeyWh1te commented on l2-bridge-zksync/src/agent-proxy-watcher.ts
> +async function getZkProxyImpl(proxyInfo: LidoZkSyncProxy, blockNumber: number) {
renamed

2023-11-17 08:03 UTC, sergeyWh1te commented on l2-bridge-zksync/src/agent-proxy-watcher.ts
> +async function getProxyImpl(proxyInfo: LidoProxy, blockNumber: number) {
Reordered. So, I'll refactor it anyway

2023-11-17 08:03 UTC, sergeyWh1te commented on l2-bridge-zksync/src/constants.ts
> +        address: proxyInfo.proxyAdminAddress,
set proxyAddress

2023-11-17 08:03 UTC, sergeyWh1te commented on l2-bridge-zksync/src/constants.ts
> +        address: proxyInfo.proxyAdminAddress,
set proxyInfo.proxyAddress

2023-11-17 08:04 UTC, sergeyWh1te commented on l2-bridge-zksync/src/constants.ts
> +        address: proxyInfo.proxyAdminAddress,
set proxyInfo.proxyAddress

2023-11-17 09:54 UTC, TheDZhon commented on l2-bridge-zksync/src/agent-proxy-watcher.ts
> +    LIDO_ZKSYNC_PROXY_CONTRACTS.map(async (proxyInfo: LidoZkSyncProxy) => {
sorry it hasn't resolved yet

2023-11-17 10:19 UTC, TheDZhon requested changes
Everything is great except only for `ProxyAdmin` exceptions :see_no_evil: 

![image](https://github.com/lidofinance/alerting-forta/assets/961317/a1e70d5f-a5bd-499b-a6c5-23a8ae8e884d)

2023-11-17 10:19 UTC, TheDZhon commented on l2-bridge-zksync/src/agent-proxy-watcher.ts
> +    await proxy.functions[adminFunc](proxyInfo.proxyAddress, {
:warning:  the function can revert if the `ProxyAdmin` instance has been changed
in this case, we should fire an alert that someone else is the proxy's admin

2023-11-17 10:19 UTC, TheDZhon commented on l2-bridge-zksync/src/agent-proxy-watcher.ts
> +    await proxy.functions[implFunc](proxyInfo.proxyAddress, {
:warning:  the function can revert if the `ProxyAdmin` instance has been changed
in this case, we should fire an alert that someone else is the proxy's admin

2023-11-17 10:47 UTC, TheDZhon approved these changes
:green_apple:

2023-11-20 09:31 UTC, vgorkavenko commented on l2-bridge-zksync/src/abi/L2ERC20Bridge.json
let's convert it to one-string json (and other abis as well)

2023-11-20 09:31 UTC, vgorkavenko commented on l2-bridge-zksync/src/agent-bridge-watcher.ts
> +export async function handleTransaction(logs: Log[]) {
it is not `logs` but `txEvent: TransactionEvent`, isn't it?

2023-11-20 09:31 UTC, vgorkavenko commented on l2-bridge-zksync/src/agent-bridge-watcher.ts
> +  L2_BRIDGE_EVENTS.forEach((eventInfo) => {
what do you think about using `handleEventsOfNotice` function? https://github.com/lidofinance/alerting-forta/blob/04f2021552611b165fedb51e2620ac2e7e31569c/ethereum-steth/src/common/utils.ts#L102

2023-11-20 09:31 UTC, vgorkavenko commented on l2-bridge-zksync/src/entity/transactionEvent.ts
> +  public static filterLog(
why did you copy that function from Forta SDK instead of just using Forta SDK?

2023-11-20 09:34 UTC, skhomuti approved these changes

2023-11-20 09:41 UTC, sergeyWh1te commented on l2-bridge-zksync/src/abi/L2ERC20Bridge.json
prettier decided to beatify abi files, i didn't became to argue with it =)

2023-11-20 09:42 UTC, sergeyWh1te commented on l2-bridge-zksync/src/agent-bridge-watcher.ts
> +export async function handleTransaction(logs: Log[]) {
That's because forta doesn't support ZkSync out of the box.

2023-11-20 09:51 UTC, sergeyWh1te commented on l2-bridge-zksync/src/entity/transactionEvent.ts
> +  public static filterLog(
That's because in forta sdk the "filterLog" function it's a part of TransactionEvent class with a contructor
```

  constructor(
    readonly type: EventType,
    readonly network: Network,
    readonly transaction: Transaction,
    readonly traces: Trace[] = [],
    readonly addresses: { [key: string]: boolean },
    readonly block: TxEventBlock,
    readonly logs: Log[] = [],
    readonly contractAddress: string | null
  ) {}
```

But for using filterLog func we need only logs objects. This why we decided to port this function with addition arguments logs intead of setting up all unnessary objects for instance TransactionEvent

2023-11-20 09:56 UTC, merged