feat: add monitoring for Base and ZkSync inside l2-bridge-ethereum bot
lidofinance/alerting-forta pull request #434
Opened 2023-11-15 15:06 UTC by sergeyWh1te

2023-11-16 09:18 UTC, TheDZhon requested changes
Thank you for shipping the change.

However, I suggest polishing up the PR's content

2023-11-16 09:18 UTC, TheDZhon commented on l2-bridge-ethereum/src/constants.ts
> +export const ZKSYNC_L1ERC20_TOKEN_BRIDGE =
```suggestion
export const ZKSYNC_L1ERC20_BRIDGE =
```

2023-11-16 09:18 UTC, TheDZhon commented on l2-bridge-ethereum/src/constants.ts
> +export const ARBITRUM_L1ERC20_TOKEN_GATEWAY =
Please consider adding proxy monitoring for `L1Executor` (zkSync part):

```js
export const ZKSYNC_L1EXECUTOR = 
    "0xFf7F4d05e3247374e86A3f7231A2Ed1CA63647F2";
```

2023-11-16 09:18 UTC, TheDZhon commented on l2-bridge-ethereum/src/constants.ts
>  export const GATEWAY_SET_EVENT =
```suggestion
export const ARBITRUM_GATEWAY_SET_EVENT =
```

2023-11-16 09:18 UTC, TheDZhon commented on l2-bridge-ethereum/src/constants.ts
>  export const ARBITRUM_L1_GATEWAY_ROUTER =
Please consider:

1) Using this constant below
![image](https://github.com/lidofinance/alerting-forta/assets/961317/bcb212ec-9ea4-4337-9fa1-72daa5eccc0f)

2) Adding Base OVM L1 Cross Domain messenger here to monitor for the same administrative events:

> L1CrossDomainMessenger	[0x866E82a600A1414e583f7F13623F1aC5d58b0Afa](https://etherscan.io/address/0x866E82a600A1414e583f7F13623F1aC5d58b0Afa)
taken from here: https://docs.base.org/base-contracts#l1-contract-addresses
ABIs and events are the same as for Optimism

3) `DiamonProxy` events from zkSync

> DiamondProxy	[0x32400084c286cf3e17e7b677ea9583e60a000324](https://etherscan.io/address/0x32400084c286cf3e17e7b677ea9583e60a000324#code)

:warning:  Please pay attention to ABIs and events; they might be different for zkSync

2023-11-16 11:39 UTC, sergeyWh1te commented on l2-bridge-ethereum/src/constants.ts
> +export const ARBITRUM_L1ERC20_TOKEN_GATEWAY =
added in another pr

2023-11-16 13:25 UTC, sergeyWh1te commented on l2-bridge-ethereum/src/abi/ProxyShortABI.json
done

2023-11-16 13:25 UTC, sergeyWh1te commented on l2-bridge-ethereum/src/constants.ts
> +export const ZKSYNC_L1ERC20_TOKEN_BRIDGE =
done

2023-11-16 13:29 UTC, sergeyWh1te commented on l2-bridge-ethereum/src/constants.ts
>  export const GATEWAY_SET_EVENT =
Do you know is the "event GatewaySet(address indexed l1Token, address indexed gateway)" same for optimism, base, arbitrum networks?

2023-11-16 13:56 UTC, sergeyWh1te commented on l2-bridge-ethereum/src/constants.ts
>  export const ARBITRUM_L1_GATEWAY_ROUTER =
done

2023-11-17 06:55 UTC, TheDZhon requested changes
I belive we are almost done :pray:

2023-11-17 06:55 UTC, TheDZhon commented on l2-bridge-ethereum/src/constants.ts
> +export const OPTIMISM_L1_GATEWAY_ROUTER =
let's call it not 'GATEWAY_ROUTER` as it's a name for the Arbitrum's violet facade contract

it's `OPTIMISM_L1_CROSS_DOMAIN_MESSENGER` (L1CrossDomainMessenger here: https://community.optimism.io/docs/useful-tools/networks/#op-mainnet)

2023-11-17 06:55 UTC, TheDZhon commented on l2-bridge-ethereum/src/constants.ts
> +export const BASE_L1_GATEWAY_ROUTER =
```suggestion
export const OPTIMISM_L1_CROSS_DOMAIN_MESSENGER =
```

2023-11-17 06:55 UTC, TheDZhon commented on l2-bridge-ethereum/src/constants.ts
> +export const ZKSYNC_L1_DIAMOND_PROXY =
:heart:

2023-11-17 06:55 UTC, TheDZhon commented on l2-bridge-ethereum/src/constants.ts
> +    name: "🚨 ZkSync Native Bridge: OVM L1 Cross Domain Messenger proxy changed",
:warning:  there is no 'OVM' for zkSync
please call it 'zkSync Diamond Proxy'

2023-11-17 07:24 UTC, sergeyWh1te commented on l2-bridge-ethereum/src/constants.ts
> +export const BASE_L1_GATEWAY_ROUTER =
I think you mean BASE_L1_CROSS_DOMAIN_MESSENGER
done

2023-11-17 09:48 UTC, TheDZhon approved these changes
Splendid :star_struck:

2023-11-20 08:58 UTC, merged