L2 bridge mantle
lidofinance/alerting-forta pull request #438
Opened 2023-12-04 14:35 UTC by sergeyWh1te

## How does it work.

This PR introduces a new bot operating on the Mantle network.
The existing bot functions on two networks: ETH mainnet and Mantle.
Here's how it operates: The bot monitors new blocks on the ETH mainnet.
Since Forta doesn't currently support Mantle, the bot reads blocks on the L2 network (Mantle) and stores the latest one
in an in-memory cache.
When the bot reads the next block on ETH, it also retrieves a segment of Mantle blocks (cachedBlock, LatestBlock) from
the cache.

## Supported chains

- Ethereum mainnet, Mantle network

## Alerts

1. Bridge events
   1. 🚨 Mantle L2 Bridge: Role Admin changed
   2. ⚠️ Mantle L2 Bridge: Role granted
   3. ⚠️ Mantle L2 Bridge: Role revoked
   4. ✅ Mantle L2 Bridge: Deposits Enabled
   5. ❌ Mantle L2 Bridge: Deposits Disabled
   6. ✅ Mantle L2 Bridge: Withdrawals Enabled
   7. ❌ Mantle L2 Bridge: Withdrawals Disabled
   8. 🚨 Mantle L2 Bridge: Implementation initialized
2. Gov Events
   1. 🚨 Mantle Gov Bridge: Ethereum Governance Executor Updated
   2. 🚨 Mantle Gov Bridge: Guardian Updated
   3. ⚠️ Mantle Gov Bridge: Delay Updated
   4. ⚠️ Mantle Gov Bridge: Grace Period Updated
   5. ⚠️ Mantle Gov Bridge: Min Delay Updated
   6. ⚠️ Mantle Gov Bridge: Max Delay Updated
   7. ℹ Mantle Gov Bridge: Action set queued
   8. ℹ Mantle Gov Bridge: Action set executed
   9. ℹ Mantle Gov Bridge: Action set canceled
3. Proxy events
   1. 🚨 Mantle: Proxy ossified
   2. 🚨 Mantle: Proxy admin changed
   3. 🚨 Mantle: Proxy upgraded
   4. 🚨 Mantle: Proxy beacon upgraded
4. Monitor Withdrawals
   1. ⚠️ Mantle: Huge withdrawals during the last ...
5. Agent balance
   1. Added wstETH: 🚨🚨🚨 Mantle bridge balance mismatch 🚨🚨🚨

## Proofs of addreses and constants got from https://docs.lido.fi/deployed-contracts/:
      
1. L1ERC20TokenBridge Impl : [0x6fBBe1Af52D22557D7F161Dc5952E306F4742e23](https://etherscan.io/address/0x2D001d79E5aF5F65a939781FE228B267a8Ed468B)
2. L1ERC20TokenBridge Proxy: [0x2D001d79E5aF5F65a939781FE228B267a8Ed468B](https://etherscan.io/address/0x6fBBe1Af52D22557D7F161Dc5952E306F4742e23)
 3. ERC20Bridged Impl: [0x1FaBaAec88198291A4efCc85Cabb33a3785165ba](https://explorer.mantle.xyz/address/0x1FaBaAec88198291A4efCc85Cabb33a3785165ba)
 4. ERC20Bridged Proxy: [0x458ed78EB972a369799fb278c0243b25e5242A83](https://explorer.mantle.xyz/address/0x458ed78EB972a369799fb278c0243b25e5242A83)
 5. L2ERC20TokenBridge Impl: [0xf10A7ffC613a9b23Abc36167925A375bf5986181](https://explorer.mantle.xyz/address/0xf10A7ffC613a9b23Abc36167925A375bf5986181)
6. L2ERC20TokenBridge Proxy: [0x9c46560D6209743968cC24150893631A39AfDe4d](https://explorer.mantle.xyz/address/0x9c46560D6209743968cC24150893631A39AfDe4d)
 7. OptimismBridgeExecutor: [0x3a7b055bf88cdc59d20d0245809c6e6b3c5819dd](https://explorer.mantle.xyz/address/0x3a7b055bf88cdc59d20d0245809c6e6b3c5819dd)

2023-12-06 19:22 UTC, TheDZhon requested changes
Thank you for bringing the refined architecture vision. :guitar: 

I would suggest addressing the findings highlighted before going further :pray:

2023-12-06 19:22 UTC, TheDZhon commented on l2-bridge-mantle/README.md
> +## How to setup new bot and network
would suggest having this guide somewhere in the top level file and have the embedded link on it within each L2 bot

2023-12-06 19:22 UTC, TheDZhon commented on l2-bridge-mantle/src/config/bot-config.json
> +    "RpcUrlBase64": "aHR0cHM6Ly9tYW50bGUucHVibGljbm9kZS5jb20="
I am a bit confused

2023-12-06 19:22 UTC, TheDZhon commented on l2-bridge-mantle/src/generated/factories/L2ERC20TokenBridge__factory.ts
Do we really need to commit generated files?

2023-12-06 19:22 UTC, TheDZhon commented on l2-bridge-mantle/src/utils/constants.ts
> +  address: '0x63f736f21cb2943826cd50b191eb054ebbea670e4e962d0527611f830cd399d6',
applicable here and there

2023-12-06 19:22 UTC, TheDZhon commented on template-v2/src/abi/L2Bridge.json
won't be a universal interface tho

2023-12-06 19:22 UTC, TheDZhon commented on template-v2/src/config/bot-config.json
> +    "RpcUrlBase64": "aHR0cHM6Ly9iYXNlLW1haW5uZXQuZy5hbGNoZW15LmNvbS92Mi9sQ0RseWdMNk00eHpVdF9KTEQxMFo3MW9pMkRfeVpiNA"
alchemy key :eyes:

2023-12-06 19:22 UTC, TheDZhon commented on template-v2/src/generated/index.ts
Are we totally sure that the `generated` contents should be committed at all I mean?

2023-12-07 12:33 UTC, sergeyWh1te commented on l2-bridge-balance/src/agent-balance.ts
> +    handleBridgeBalanceLDO(blockEvent, findings, BRIDGE_PARAMS_LDO.Optimism),
fixed

2023-12-07 12:34 UTC, sergeyWh1te commented on l2-bridge-balance/src/constants.ts
> +    rpcUrl: config.ZkSync.RpcUrl,
fixed

2023-12-07 13:26 UTC, sergeyWh1te commented on l2-bridge-mantle/src/generated/factories/L2ERC20TokenBridge__factory.ts
Yes, we need

2023-12-07 13:28 UTC, sergeyWh1te commented on l2-bridge-mantle/src/utils/constants.ts
> +  address: '0x63f736f21cb2943826cd50b191eb054ebbea670e4e962d0527611f830cd399d6',
fixed

2023-12-07 13:30 UTC, sergeyWh1te commented on template-v2/src/config/bot-config.json
> +    "RpcUrlBase64": "aHR0cHM6Ly9iYXNlLW1haW5uZXQuZy5hbGNoZW15LmNvbS92Mi9sQ0RseWdMNk00eHpVdF9KTEQxMFo3MW9pMkRfeVpiNA"
fix

2023-12-07 13:30 UTC, sergeyWh1te commented on template-v2/src/generated/index.ts
yes

2023-12-07 17:18 UTC, sergeyWh1te commented on l2-bridge-mantle/src/config/bot-config.json
> +    "RpcUrlBase64": "aHR0cHM6Ly9tYW50bGUucHVibGljbm9kZS5jb20="
fixed

2023-12-08 07:22 UTC, TheDZhon commented on README.md
> +## How to setup new bot and network on example from template-v2 folder or l2-bridge-mantle
I am not totally convinced that we should populate top-level README with L2-specifics :warning:

2023-12-08 07:25 UTC, TheDZhon commented on l2-bridge-ethereum/src/constants.ts
> +export const ZKSYNC_L1ERC20_TOEKEN_BRIDGE =
```suggestion
export const ZKSYNC_L1ERC20_TOKEN_BRIDGE =
```

2023-12-08 07:25 UTC, TheDZhon commented on l2-bridge-ethereum/src/constants.ts
> +    address: ZKSYNC_L1ERC20_TOEKEN_BRIDGE,
```suggestion
    address: ZKSYNC_L1ERC20_TOKEN_BRIDGE,
```

2023-12-08 08:13 UTC, sergeyWh1te commented on README.md
> +## How to setup new bot and network on example from template-v2 folder or l2-bridge-mantle
moved

2023-12-08 08:15 UTC, sergeyWh1te commented on l2-bridge-ethereum/src/constants.ts
> +export const ZKSYNC_L1ERC20_TOEKEN_BRIDGE =
fix

2023-12-08 08:16 UTC, sergeyWh1te commented on l2-bridge-ethereum/src/constants.ts
> +    address: ZKSYNC_L1ERC20_TOEKEN_BRIDGE,
fix

2023-12-08 08:16 UTC, sergeyWh1te commented on l2-bridge-ethereum/src/constants.ts
> +    address: ZKSYNC_L1ERC20_TOEKEN_BRIDGE,
fix

2023-12-08 08:24 UTC, sergeyWh1te commented on l2-bridge-mantle/src/utils/constants.ts
> +export const WITHDRAWAL_INITIATED_EVENT =
I got it from here. Are sure, that are the same?
https://github.com/mantlenetworkio/lido-l2/blob/main/contracts/mantle/interfaces/IL2ERC20Bridge.sol#L11

2023-12-08 08:25 UTC, sergeyWh1te commented on l2-bridge-mantle/src/utils/constants.ts
> +// TODO ask
fix

2023-12-11 07:20 UTC, TheDZhon commented on l2-bridge-mantle/src/utils/constants.ts
> +export const WITHDRAWAL_INITIATED_EVENT =
Oh, it's a good catch indeed :1st_place_medal: 

Looks like the one you pasted here is correct, but Optimism and Base alerts both contain incorrect signature definition! Please update 'em.

As I see, they have the signature copy-pasted from Arbitrum, ugh.

2023-12-11 07:22 UTC, TheDZhon requested changes
Thank you! It's the only single step is left :rocket:  (concerning the Opti/Base event signatures)

2023-12-11 07:22 UTC, TheDZhon commented on l2-bridge-mantle/src/utils/constants.ts
> +  'event WithdrawalInitiated( address indexed _l1Token, address indexed _l2Token, address indexed _from, address _to, uint256 _amount, bytes _data)'
```suggestion
  'event WithdrawalInitiated(address indexed _l1Token, address indexed _l2Token, address indexed _from, address _to, uint256 _amount, bytes _data)'
```

2023-12-11 15:29 UTC, TheDZhon requested changes
Done a review pass, and found some changes to be done

2023-12-11 15:29 UTC, TheDZhon commented on l2-bridge-ethereum/src/constants.ts
> +export const ZKSYNC_L1ERC20_TOKEN_BRIDGE =
The actual contract is named as it was before this PR

```suggestion
export const ZKSYNC_L1ERC20_BRIDGE =
```

2023-12-11 15:53 UTC, TheDZhon approved these changes
LGTM

2023-12-11 15:56 UTC, dgusakov approved these changes
Approved with no detailed review

2023-12-11 15:59 UTC, merged