feat: l2-bridge-linea
lidofinance/alerting-forta pull request #448
Opened 2023-12-14 13:19 UTC by sergeyWh1te

2023-12-14 19:24 UTC, TheDZhon requested changes
🫡 Thank you!

I suggest implementing some edits to improve the code.

2023-12-14 19:24 UTC, TheDZhon commented on l2-bridge-ethereum/src/constants.ts
> +      `Proxy admin for Linea: OVM L1 Cross Domain Messenger ` +
```suggestion
      `Proxy admin for Linea: L1 Token Bridge ` +
```

2023-12-14 19:24 UTC, TheDZhon commented on l2-bridge-linea/README.md
> +   3. ⚠️ Linea L2 Bridge: Role revoked
Have no roles for this bridge tho :warning:

2023-12-14 19:24 UTC, TheDZhon commented on l2-bridge-linea/README.md
> +   7. ❌ Linea L2 Bridge: Withdrawals Disabled
has only 'paused' and 'not paused' global states

2023-12-14 19:24 UTC, TheDZhon commented on l2-bridge-linea/README.md
> +   1. 🚨 Linea: Proxy ossified
have no 'ossified' state

2023-12-14 19:24 UTC, TheDZhon commented on l2-bridge-linea/src/abi/L2ERC20TokenBridge.json
sorry, I am afraid, it's a wrong ABI

2023-12-14 19:24 UTC, TheDZhon commented on l2-bridge-linea/src/abi/OssifiableProxy.json
Have no `OssifiableProxy` here at all on Linea

2023-12-14 19:24 UTC, TheDZhon commented on l2-bridge-linea/src/abi/OssifiableProxy.json
but have:
- `TransparentUpgadeableProxy`
- `ProxyAdmin`

2023-12-14 19:24 UTC, TheDZhon commented on l2-bridge-linea/src/agent.ts
I am wondering if we can extract all of the repetitive boilerplate to `utils` and import them for each bot

2023-12-14 19:24 UTC, TheDZhon commented on l2-bridge-linea/src/agent.ts
(for future reference)

2023-12-14 19:24 UTC, TheDZhon commented on l2-bridge-linea/src/clients/forta_guard_client.ts
> +    // return Buffer.from('aHR0cHM6Ly9ycGMubWFudGxlLnh5eg==', 'base64').toString('utf-8')
```suggestion
```

2023-12-14 19:24 UTC, TheDZhon commented on l2-bridge-linea/src/entity/proxy_contract.ts
Should use `ProxyAdmin` for retrieving the data
Like here: https://github.com/lidofinance/alerting-forta/blob/main/l2-bridge-zksync/src/agent-proxy-watcher.ts#L70-L128

2023-12-14 19:24 UTC, TheDZhon commented on l2-bridge-linea/src/entity/role.ts
Doesn't have roles

2023-12-14 19:24 UTC, TheDZhon commented on l2-bridge-linea/src/utils/constants.ts
> +  'event WithdrawalInitiated(address indexed _l1Token, address indexed _l2Token, address indexed _from, address _to, uint256 _amount, bytes _data)'
```suggestion
export const BRIDGING_INITIATED_EVENT =
  'event BridgingInitiated(address indexed sender, address recipient, address indexed token, uint256 indexed amount)'
```

2023-12-14 19:24 UTC, TheDZhon commented on l2-bridge-linea/src/utils/constants.ts
> +  'event WithdrawalInitiated(address indexed _l1Token, address indexed _l2Token, address indexed _from, address _to, uint256 _amount, bytes _data)'
source: https://lineascan.build/address/0x2bfdf4a0d54c93a4baf74f8dcea8a275d8ee97a9#code#F32#L7

2023-12-14 19:24 UTC, TheDZhon commented on l2-bridge-linea/src/utils/constants.ts
> +  name: 'L2_ERC20_TOKEN_GATEWAY',
```suggestion
  name: 'L2_ERC20_TOKEN_BRIDGE',
```

2023-12-14 19:24 UTC, TheDZhon commented on l2-bridge-linea/src/utils/events/bridge_events.ts
> +      'event RoleAdminChanged(bytes32 indexed role, bytes32 indexed previousAdminRole, bytes32 indexed newAdminRole)',
have no roles at all

2023-12-14 19:24 UTC, TheDZhon commented on l2-bridge-linea/src/utils/events/bridge_events.ts
> +    event: 'event RoleGranted(bytes32 indexed role, address indexed account, address indexed sender)',
have no roles at all

2023-12-14 19:24 UTC, TheDZhon commented on l2-bridge-linea/src/utils/events/bridge_events.ts
> +    event: 'event RoleRevoked(bytes32 indexed role, address indexed account, address indexed sender)',
have no roles at all

2023-12-14 19:24 UTC, TheDZhon commented on l2-bridge-linea/src/utils/events/bridge_events.ts
> +    event: 'event DepositsEnabled(address indexed enabler)',
Have only two events instead of more granular ones:

```solidity
    /**
     * @dev Emitted when the pause is triggered by `account`.
     */
    event Paused(address account);

    /**
     * @dev Emitted when the pause is lifted by `account`.
     */
    event Unpaused(address account);
```
see: https://lineascan.build/address/0x2bfdf4a0d54c93a4baf74f8dcea8a275d8ee97a9#code#F5#L19
    
Instead of more granular ones

2023-12-14 19:24 UTC, TheDZhon commented on l2-bridge-linea/src/utils/events/bridge_events.ts
> +    event: 'event Initialized(address indexed admin)',
```suggestion
    event: 'event Initialized(uint8 version)',
```
see: https://lineascan.build/address/0x2bfdf4a0d54c93a4baf74f8dcea8a275d8ee97a9#code#F4#L73

2023-12-14 19:24 UTC, TheDZhon commented on l2-bridge-linea/src/utils/events/proxy_admin_events.ts
> +        event: 'event ProxyOssified()',
have no such an event at all

2023-12-15 09:59 UTC, sergeyWh1te commented on l2-bridge-balance/src/agent-balance.ts
> +      BRIDGE_PARAMS_WSTETH.Mantle,
fix

2023-12-15 10:00 UTC, sergeyWh1te commented on l2-bridge-ethereum/src/constants.ts
> +export const LINEA_L1ERC20_TOKEN_BRIDGE =
fix

2023-12-15 10:00 UTC, sergeyWh1te commented on l2-bridge-ethereum/src/constants.ts
> +    address: LINEA_L1ERC20_TOKEN_BRIDGE,
fix

2023-12-15 10:02 UTC, sergeyWh1te commented on l2-bridge-ethereum/src/constants.ts
> +    shortABI: JSON.stringify(ossifiableProxyShortABI),
What is the correct argument for calling proxyAdmin, proxyImp?

2023-12-15 10:13 UTC, sergeyWh1te commented on l2-bridge-ethereum/src/constants.ts
> +      "event AddressSet(string indexed _name, address _newAddress, address _oldAddress)",
addde

2023-12-15 10:14 UTC, sergeyWh1te commented on l2-bridge-ethereum/src/constants.ts
> +    name: "🚨 Linea Native Bridge: OVM L1 Cross Domain Messenger proxy upgraded",
fix

2023-12-15 10:14 UTC, sergeyWh1te commented on l2-bridge-ethereum/src/constants.ts
> +      `Proxy for Linea: Proxy OVM L1 Cross Domain Messenger ` +
fix

2023-12-15 10:22 UTC, sergeyWh1te commented on l2-bridge-ethereum/src/constants.ts
> +    name: "🚨 Linea Native Bridge: OVM L1 Cross Domain Messenger proxy admin changed",
added

2023-12-15 10:23 UTC, sergeyWh1te commented on l2-bridge-ethereum/src/constants.ts
> +      `Proxy admin for Linea: OVM L1 Cross Domain Messenger ` +
fix

2023-12-15 10:26 UTC, sergeyWh1te commented on l2-bridge-linea/README.md
> +   3. ⚠️ Linea L2 Bridge: Role revoked
rmd

2023-12-15 10:26 UTC, sergeyWh1te commented on l2-bridge-linea/README.md
> +   7. ❌ Linea L2 Bridge: Withdrawals Disabled
rmd

2023-12-15 10:27 UTC, sergeyWh1te commented on l2-bridge-linea/README.md
> +   1. 🚨 Linea: Proxy ossified
rmd

2023-12-15 10:35 UTC, sergeyWh1te commented on l2-bridge-linea/src/agent.ts
It's a pretty getting thing to do it. But we have a limitation with FORTA-sdk. It's impossible to import external code placed not in src folder. For achieving this we have to switch up our development vision to grpc approach, not ts-js injection idea into forta-sdk source code

2023-12-15 11:27 UTC, sergeyWh1te commented on l2-bridge-linea/src/utils/constants.ts
> +  'event WithdrawalInitiated(address indexed _l1Token, address indexed _l2Token, address indexed _from, address _to, uint256 _amount, bytes _data)'
fixed

2023-12-15 11:28 UTC, sergeyWh1te commented on l2-bridge-linea/src/utils/constants.ts
> +  name: 'L2_ERC20_TOKEN_GATEWAY',
fixed

2023-12-15 11:28 UTC, sergeyWh1te commented on l2-bridge-linea/src/utils/events/bridge_events.ts
> +      'event RoleAdminChanged(bytes32 indexed role, bytes32 indexed previousAdminRole, bytes32 indexed newAdminRole)',
rmd

2023-12-15 11:28 UTC, sergeyWh1te commented on l2-bridge-linea/src/utils/events/bridge_events.ts
> +    event: 'event RoleGranted(bytes32 indexed role, address indexed account, address indexed sender)',
rmd

2023-12-15 11:28 UTC, sergeyWh1te commented on l2-bridge-linea/src/utils/events/bridge_events.ts
> +    event: 'event RoleRevoked(bytes32 indexed role, address indexed account, address indexed sender)',
rmd

2023-12-15 11:35 UTC, sergeyWh1te commented on l2-bridge-linea/src/utils/events/bridge_events.ts
> +    event: 'event Initialized(address indexed admin)',
added

2023-12-15 11:36 UTC, sergeyWh1te commented on l2-bridge-linea/src/utils/events/proxy_admin_events.ts
> +        event: 'event ProxyOssified()',
rmd

2023-12-22 13:41 UTC, sergeyWh1te commented on l2-bridge-linea/README.md
> +    2. ✅ Linea L2 Bridge: Not paused
fixed

2023-12-22 15:01 UTC, sergeyWh1te commented on l2-bridge-ethereum/src/constants.ts
> +    shortABI: JSON.stringify(ossifiableProxyShortABI),
fixed

2024-01-10 11:00 UTC, TheDZhon approved these changes
LGTM, tho the README file need a bit of polishing :pray:

2024-01-10 11:00 UTC, TheDZhon commented on l2-bridge-linea/README.md
> +## Alerts
I believe this list is a bit out of sync with the actual alerts (e.g., custom token set)

2024-01-10 11:00 UTC, TheDZhon commented on l2-bridge-linea/README.md
> +## Alerts
![image](https://github.com/lidofinance/alerting-forta/assets/961317/56e70b90-5f94-4010-9f66-8f0d67bac832)

2024-01-10 11:10 UTC, sergeyWh1te commented on l2-bridge-linea/README.md
> +## Alerts
not in this pr

2024-01-10 11:19 UTC, dgusakov approved these changes

2024-01-10 11:20 UTC, merged