VAL-530: Check Aragon ACL alerts for Simple DVT (Forta)
lidofinance/alerting-forta pull request #458
Opened 2024-01-14 05:35 UTC by AlexandrMov

- simpledvt alerting
- holesky testnet support

2024-01-15 11:38 UTC, dgusakov requested changes

2024-01-15 13:20 UTC, AlexandrMov commented on ethereum-governance/e2e/__snapshots__/agent-proxy-watcher.e2e-spec.ts.snap
> +    "description": "Implementation of Curated NO Registry ([0x55032650b14df07b85bf18a3a3ec8e0af2e028d5](https://etherscan.io/address/0x55032650b14df07b85bf18a3a3ec8e0af2e028d5)) changed from [0xec356
The test already has ordering by description. I can suggest whether to adjust the name of alert only or change snapshot directly.

2024-01-15 13:22 UTC, AlexandrMov commented on ethereum-governance/src/common/constants.testnet.ts
> +export const CURATED_NODE_OPERATORS_REGISTRY_ADDRESS =
I renamed those files

2024-01-16 08:24 UTC, dgusakov approved these changes

2024-01-31 18:27 UTC, sergeyWh1te commented
My main question for all pull requests. Are there unit tests?

2024-02-01 10:58 UTC, AlexandrMov commented
> My main question for all pull requests. Are there unit tests?

There no e2e tests due to simpleDVT has not been deployed on Mainnet yet. I thought to add e2e tests once the new module is deployed. I suggest it would be a separate task.

2024-02-23 13:54 UTC, infloop approved these changes

2024-02-23 15:01 UTC, BATMAH69 approved these changes

2024-02-23 15:07 UTC, BATMAH69 requested changes

2024-02-23 15:07 UTC, BATMAH69 commented on ethereum-governance/src/subagents/easy-track/constants.holesky.ts
> +export const EASY_TRACK_TYPES_BY_FACTORIES = new Map<string, string>([
looks like addresses from goerly

2024-02-23 15:54 UTC, AlexandrMov commented on ethereum-governance/src/subagents/easy-track/constants.holesky.ts
> +export const EASY_TRACK_TYPES_BY_FACTORIES = new Map<string, string>([
We had a conversation about easy tracks. That the gov bot owners will upgrade easy tracks themselves. I just added the holesky network supporting.

2024-02-23 15:59 UTC, BATMAH69 approved these changes

2024-02-23 16:05 UTC, merged