Eth steth
lidofinance/alerting-forta pull request #459
Opened 2024-01-17 12:02 UTC by sergeyWh1te

## Alerts

1. StETH operations
    1. HandleBlock
        1. 🚨🚨🚨 Buffered ETH drain (checks each block)
        2. 🚨 Huge depositable ETH amount (checks every 100 blocks)
        3. ⚠️ High depositable ETH amount (checks every 100 blocks)
        4. ⚠️ Low deposit executor balance (checks every 100 blocks)
        5. ⚠️ Staking limit below 10% (checks every 25 blocks)
        6. 📉 Staking limit below 30% (checks every 25 blocks)
    2. HandleTransaction
        1. Deposit Security events
            1. 🚨 Deposit Security: Deposits paused
            2. ✅ Deposit Security: Deposits resumed
            3. ⚠️ Deposit Security: Guardian added
            4. ⚠️ Deposit Security: Guardian removed
            5. 🚨 Deposit Security: Guardian quorum changed
            6. ⚠️ Deposit Security: Max deposits changed
            7. ⚠️ Deposit Security: Min deposit block distance changed
            8. 🚨 Deposit Security: Owner changed
        2. Lido events
            1. 🚨🚨🚨 Lido: Stopped 🚨🚨🚨
            2. ✅ Lido: Resumed
            3. 🚨 Lido: Staking paused
            4. ✅ Lido: Staking resumed
            5. ⚠️ Lido: Staking limit set
            6. 🚨 Lido: Staking limit removed
            7. 🚨 Lido: Locator set
            8. ℹ️ Lido: Funds recovered to vault
            9. ℹ️ Lido: Contract version set
        3. Insurance fund events
            1. ⚠️ Insurance fund: ETH transferred
            2. ⚠️ Insurance fund: ERC721 transferred
            3. 🚨 Insurance fund: ERC20 transferred
            4. ⚠️ Insurance fund: ERC1155 transferred
            5. 🚨 Insurance fund: Ownership transferred
        4. Burner events
            1. ℹ️ Lido Burner: ERC20 recovered
            2. ℹ️ Lido Burner: ERC721 recovered
2. Withdrawals.
    1. HandleBlock runs on each 100-th block or one per 20 minutes
        1. ⚠️ Withdrawals: <limitRate>% of stake limit is drained and unfinalized queue is on par with drained stake
           limit
        2. ⚠️ Withdrawals: unfinalized queue is more than 100_000 stETH
        3. ⚠️ Withdrawals: unfinalized queue wait time is too long
        4. 🤔 Withdrawals: ${unclaimedSizeRate.times(100).toFixed(2)}% of finalized requests are unclaimed
        5. 🤔 Withdrawals: unclaimed requests size is more than withdrawal queue balance
    2. HandleTransaction
        1. 🚨 Withdrawals: BUNKER MODE ON! 🚨
        2. ✅ Withdrawals: BUNKER MODE OFF! ✅
        3. ℹ️ Huge stETH withdrawal requests batch
        4. ⚠️ Withdrawals: the sum of received withdrawal requests since the last rebase greater than 150_000 stETH
        5. 🤔 Withdrawals: claimed amount is more than requested
        6. ✅ Withdrawals: contract was unpaused
        7. 🚨 Withdrawals: contract was paused
3. GateSeal
    1. HandleBlock runs on each next block
        1. ⚠️ GateSeal: default GateSeal address in forta agent is expired
        2. ⚠️️ GateSeal: default GateSeal address in forta agent doesn't have PAUSE_ROLE for contracts
        3. 🚨GateSeal: actual address doesn't have PAUSE_ROLE for contracts
        4. 🚨🚨🚨 GateSeal: is expired! 🚨🚨🚨
        5. ⚠️ GateSeal: is about to be expired
    2. HandleTransaction
        1. 🚨🚨🚨 GateSeal: is sealed 🚨🚨🚨
        2. 🚨 GateSeal: new one created
4. Vaults
    1. Handleblock
        1. 💵 Withdrawal Vault Balance significant change (checks every on 100-th block)
        2. 💵 EL Vault Balance significant change
        3. 🚨 Withdrawal Vault balance mismatch
        4. 🚨 EL Vault balance mismatch
    2. HandleTransaction
        1. 🚨 Burner shares transfer

2024-01-17 13:59 UTC, arwer13 reviewed
Going to review more, please don't merge yet if no hurry

2024-01-17 13:59 UTC, arwer13 commented on ethereum-steth-v2/README.md
> +      5. ⚠️ Staking limit below 10% (checks every 25 blocks)
```suggestion
      5. ⚠️ Unspent staking limit below 10% (checks every 25 blocks)
```

2024-01-17 13:59 UTC, arwer13 commented on ethereum-steth-v2/README.md
> +      6. 📉 Staking limit below 30% (checks every 25 blocks)
```suggestion
      6. 📉 Unspent staking limit below 30% (checks every 25 blocks)
```

2024-01-17 13:59 UTC, arwer13 commented on ethereum-steth-v2/README.md
> +         2. ✅ Deposit Security: Deposits resumed
```suggestion
         2. 🚨 Deposit Security: Deposits resumed
```
Should 🚨 because It has the same semantic level as "Deposits paused"
The same for `✅ Lido: Resumed and`, `✅ Lido: Staking resumed`, `✅ Withdrawals: BUNKER MODE OFF! ✅`, `✅ Withdrawals: contract was unpaused`.
Although for some of them is should be less i think. It is at least a warning.

2024-01-17 13:59 UTC, arwer13 commented on ethereum-steth-v2/README.md
> +         1. 🚨🚨🚨 Lido: Stopped 🚨🚨🚨
Do we need both `🚨🚨🚨` and `🚨` actually?

2024-01-24 12:01 UTC, TheDZhon requested changes
Pretty good, thank you! :+1: 

Left some suggestions and considerations.

2024-01-24 12:06 UTC, sergeyWh1te commented on ethereum-steth-v2/src/agent.ts
> +      process.exit(1)
on init - yes

2024-01-24 16:31 UTC, sergeyWh1te commented on ethereum-steth-v2/README.md
> +      5. ⚠️ Staking limit below 10% (checks every 25 blocks)
done

2024-01-24 16:32 UTC, sergeyWh1te commented on ethereum-steth-v2/README.md
> +      6. 📉 Staking limit below 30% (checks every 25 blocks)
done

2024-01-24 16:38 UTC, sergeyWh1te commented on ethereum-steth-v2/README.md
> +         2. ✅ Deposit Security: Deposits resumed
set ⚠️ for all of them

2024-01-24 16:40 UTC, sergeyWh1te commented on ethereum-steth-v2/README.md
> +      1. ⚠️ Withdrawals: <limitRate>% of stake limit is drained and unfinalized queue is on par with drained stake
done

2024-01-24 16:44 UTC, sergeyWh1te commented on ethereum-steth-v2/README.md
> +      2. ✅ Withdrawals: BUNKER MODE OFF! ✅
done

2024-01-24 16:47 UTC, sergeyWh1te commented on ethereum-steth-v2/README.md
> +      4. ⚠️ Withdrawals: the sum of received withdrawal requests since the last rebase greater than 150_000 stETH
done

2024-01-24 16:53 UTC, sergeyWh1te commented on ethereum-steth-v2/README.md
> +      6. ✅ Withdrawals: contract was unpaused
done

2024-01-24 16:53 UTC, sergeyWh1te commented on ethereum-steth-v2/README.md
> +      4. 🚨🚨🚨 GateSeal: is expired! 🚨🚨🚨
done

2024-01-24 16:54 UTC, sergeyWh1te commented on ethereum-steth-v2/README.md
> +      3. 🚨GateSeal: actual address doesn't have PAUSE_ROLE for contracts
done

2024-01-24 16:55 UTC, sergeyWh1te commented on ethereum-steth-v2/README.md
> +      3. 🚨 Withdrawal Vault balance mismatch
done

2024-01-24 16:57 UTC, sergeyWh1te commented on ethereum-steth-v2/package.json
> +  "version": "0.0.1",
bumped

2024-01-24 16:58 UTC, sergeyWh1te commented on ethereum-steth-v2/src/utils/constants.testnet.ts
I'm not sure that we have to set testnet constants at all. I just moved code. Actually, I'd remove them

2024-01-24 17:00 UTC, sergeyWh1te commented on ethereum-steth-v2/src/utils/contract_mocks/contract_mocks.ts
> +        address: '0xae7ab96520de3a18e5e111b5eaab095312d7fe84',
changed to faker data

2024-01-24 17:00 UTC, sergeyWh1te commented on ethereum-steth-v2/src/utils/contract_mocks/contract_mocks.ts
> +        address: '0x889edc2edab5f40e902b864ad4d7ade8e412f9b1',
also changed

2024-01-24 17:00 UTC, sergeyWh1te commented on ethereum-steth-v2/src/utils/contract_mocks/contract_mocks.ts
> +        topics: ['0x76a397bea5768d4fca97ef47792796e35f98dc81b16c1de84e28a818e1f97108'],
also changed

2024-01-24 17:00 UTC, sergeyWh1te commented on ethereum-steth-v2/src/utils/contract_mocks/contract_mocks.ts
> +        topics: ['0x197874c72af6a06fb0aa4fab45fd39c7cb61ac0992159872dc3295207da7e9eb'],
changed

2024-01-24 17:15 UTC, sergeyWh1te commented on ethereum-steth-v2/README.md
> +      2. 🚨 GateSeal: new one created
done

2024-01-25 11:42 UTC, arwer13 commented on ethereum-steth-v2/README.md
> +      5. 🤔 Withdrawals: claimed amount is more than requested
why?

2024-01-25 11:42 UTC, arwer13 commented on ethereum-steth-v2/src/services/withdrawals/Withdrawals.srv.ts
> +              type: FindingType.Suspicious,
Let's stop using type at all? It creates confusion, but what value does it add? E.g. for this alert the severity is `critical` although in the readme it is `🤔 Withdrawals: claimed amount is more than requested` which hides it is critical.

2024-01-25 12:05 UTC, arwer13 commented on ethereum-steth-v2/src/agent.ts
> +        description: `Version: ${Version.desc}`,
Let's add some scanner/running/nodeoperator id to description here - I recon it would help to debug specific runner related problems. To description because thus it gonna be visible in the table in forta bot alerts UI

Forta guys replied how to achieve it:
> the bot can request a JWT from the node which contains the scanner address and is signed by the scanners private key. you could find out the scanner address from there at start up.
> https://docs.forta.network/en/latest/jwt-auth/

2024-01-25 16:40 UTC, sergeyWh1te commented on ethereum-steth-v2/README.md
> +      3. ⚠️ Withdrawals: unfinalized queue wait time is too long
done

2024-01-25 16:40 UTC, sergeyWh1te commented on ethereum-steth-v2/src/utils/constants.testnet.ts
removed

2024-01-25 17:18 UTC, sergeyWh1te commented on ethereum-steth-v2/README.md
> +      5. 🤔 Withdrawals: claimed amount is more than requested
Renamed to
⚠️ Withdrawals: claimed amount is more than requested

2024-01-25 17:19 UTC, sergeyWh1te commented on ethereum-steth-v2/README.md
> +1. StETH operations
implemented

2024-01-25 17:23 UTC, sergeyWh1te commented on ethereum-steth-v2/src/services/withdrawals/Withdrawals.srv.ts
> +              type: FindingType.Suspicious,
from forta sdk

```typescript
  static fromObject({
    name,
    description,
    alertId,
    protocol = 'ethereum',
    severity,
    type,
    timestamp = new Date(Math.floor(Date.now() / 1000) * 1000),
    metadata = {},
    addresses = [],
    labels = [],
    uniqueKey = '',
    source = {},
  }: FindingInput) {
    assertIsNonEmptyString(name, 'name')
    assertIsNonEmptyString(description, 'description')
    assertIsNonEmptyString(alertId, 'alertId')
    assertIsNonEmptyString(protocol, 'protocol')
    assertIsFromEnum(severity, FindingSeverity, 'severity')
    assertIsFromEnum(type, FindingType, 'type')
    // TODO assert metadata keys and values are strings

    labels = labels.map(l => l instanceof Label ? l : Label.fromObject(l))

    return new Finding(name, description, alertId, protocol, severity, type, metadata, addresses, labels, uniqueKey, source, timestamp)
  }
  ```
  
  where, **assertIsFromEnum(type, FindingType, 'type')**
 ```typescript
 export const assertIsFromEnum = (value: any, Enum: any, varName: string) => {
  if (!Object.values(Enum).includes(value)) {
    throw new Error(`${varName} must be valid enum value`);
  }
}
```

So, "type" - is required field.

But I do agree. I'd remove it at all

2024-01-25 21:12 UTC, arwer13 reviewed
Huuuuge 🐘🚀

Left some comments, going to bake more later.
I know lots of the are related to the copied code, sorry. But it looks like a good opportunity to review and improved already existed codebase.

2024-01-25 21:12 UTC, arwer13 commented on ethereum-steth-v2/src/clients/eth_provider.ts
> +      return E.left(new Error(`Could not fetch transaction history for last 3 days. Cause ${error}`))
Why 3 days? If `batchSize = 10_000` is number of blocks then `(10_000 * 12) / (24*60*60)` is approx `1.39` days

2024-01-25 21:12 UTC, arwer13 commented on ethereum-steth-v2/src/clients/eth_provider.ts
> +      return E.left(new Error(`Could not fetch balance by address ${address}. cause: ${e}`))
Capital `c` in `cause` or comma instead of dot before it, please
At least I stumble upon stuff like that :(

2024-01-25 21:12 UTC, arwer13 commented on ethereum-steth-v2/src/clients/eth_provider.ts
> +      return E.left(new Error(`Could not call "lidoContract.getStakeLimitFullInfo. Cause ${e}`))
missing closing `"`

2024-01-25 21:12 UTC, arwer13 commented on ethereum-steth-v2/src/entity/metadata.ts
> +export type Metadata = { [key: string]: string }
Btw, why having so many separate files to define types? E.g. it could be just `entities.ts` instead of folders. Imho, lots of files with ~ 10 lines of code degrade redeability

2024-01-25 21:12 UTC, arwer13 commented on ethereum-steth-v2/src/clients/eth_formatter.ts
> +import { Formatter } from '@ethersproject/providers'
There are at least 3 file name formats mixed, let's fix it! We could do it right in this PR conveniently because anyway  the files are newly added

2024-01-26 09:21 UTC, sergeyWh1te commented on ethereum-steth-v2/src/agent.ts
> +    const [stethOperationSrvErr, withdrawalsSrvErr, gateSealSrvErr] = await Promise.all([
```typesccript
  public initialize(currentBlock: number): null {
    const start = new Date().getTime()
    this.logger.info(elapsedTime(`[${this.name}.initialize] on ${currentBlock}`, start))

    return null
  }
  ```
 No. It does not missed.

2024-01-26 09:22 UTC, sergeyWh1te commented on ethereum-steth-v2/src/app.ts
> +        address.EXITBUS_ORACLE_ADDRESS,
done

2024-01-26 09:23 UTC, sergeyWh1te commented on ethereum-steth-v2/src/entity/gate_seal.ts
> +  exitbusOracleAddress: string
done

2024-01-26 09:26 UTC, sergeyWh1te commented on ethereum-steth-v2/src/clients/eth_provider.ts
> +      return E.left(new Error(`Could not fetch transaction history for last 3 days. Cause ${error}`))
fixed

2024-01-26 09:33 UTC, sergeyWh1te commented on ethereum-steth-v2/src/clients/eth_provider.ts
> +      return E.left(new Error(`Could not call "lidoContract.getStakeLimitFullInfo. Cause ${e}`))
fixed

2024-01-26 09:36 UTC, sergeyWh1te commented on ethereum-steth-v2/src/entity/metadata.ts
> +export type Metadata = { [key: string]: string }
Each entity has her namespace, not common. 
Opposite, so more order than everything in one file.

2024-01-26 09:45 UTC, sergeyWh1te commented on ethereum-steth-v2/src/agent.ts
> +    metadata.agents = '[' + agents.toString() + ']'
No. I specially removed some specific "js" techniques. We've agreed about it when I texted vision how agents have to look.

So, from a technical perspective, there is no sense. (Not good, not worse)
Also, I'd personally remove 
```typescript
  const metadata: Metadata = {
    'version.commitHash': Version.commitHash,
    'version.commitMsg': Version.commitMsg,
  }
  ```
  Because there is no a sense. All bots run from their latest version.

2024-01-26 09:50 UTC, sergeyWh1te commented on ethereum-steth-v2/src/agent.ts
> +    const [bufferedEthFindings, withdrawalsFindings, gateSealFindings, vaultFindings] = await Promise.all([
I'd prefer to leave it as it is.
Yes, this option is more technical. But no better and no worse.

But, in the one that already exists, you can see in your "hands" what is happening.

Speaking about "matches"
Also, using flat - will create new array
```typescript
  The flat() method creates a new array with all sub-array elements concatenated into it recursively up to the specified depth.
  Params:
  depth – The depth level specifying how deep a nested array structure should be flattened. Defaults to 1.  
  Returns:
  A new array with the sub-array elements concatenated into it.
  Supported by:
  Chrome 69, Chrome Android 69, Edge 79, Firefox 62, Opera 56, Safari 12, Safari iOS 12, Node.js 11.0.0, Deno
  By Mozilla Contributors , CC BY-SA 2.5 
```

2024-01-26 09:53 UTC, sergeyWh1te commented on ethereum-steth-v2/src/services/steth_operation/StethOperation.srv.ts
> +          name: `Error in ${StethOperationSrv.name}.${this.handleInvariants.name}:136`,
Then we have to think about unique names from technical alerts. Because it wouldn't be easy then to find them

2024-01-26 09:56 UTC, sergeyWh1te commented on ethereum-steth-v2/src/services/steth_operation/StethOperation.srv.ts
> +  public async handleInvariants(blockNumber: number): Promise<Finding[]> {
I didn't get you about "Also it creates corner case level up:"

But in code I wanted to show that, handleInvariants is something different then just handleBlock.

2024-01-26 09:57 UTC, sergeyWh1te commented on ethereum-steth-v2/src/clients/eth_provider.ts
> +    // const out: TransactionResponse[] = []
removed

2024-01-26 10:00 UTC, sergeyWh1te commented on ethereum-steth-v2/src/clients/eth_provider.ts
> +          { delay: 500, maxTry: 5 },
done

2024-01-26 10:02 UTC, sergeyWh1te commented on ethereum-steth-v2/src/agent.ts
> +    if (gateSealSrvErr instanceof Error) {
gateSealSrvErr - is little bit different beacuse it returns a fiding

2024-01-26 10:02 UTC, sergeyWh1te commented on ethereum-steth-v2/src/agent.ts
> +let isHandleBLockRunning: boolean = false
fixed

2024-01-26 10:04 UTC, sergeyWh1te commented on ethereum-steth-v2/src/services/steth_operation/StethOperation.srv.ts
> +        const percentsFromReporedShareRate = shareRate.right.div(shareRateFromReport.amount).multipliedBy(100)
fixed

2024-01-26 13:10 UTC, sergeyWh1te commented on ethereum-steth-v2/src/clients/eth_formatter.ts
> +import { Formatter } from '@ethersproject/providers'
renamed files with snack cases except classes

2024-01-26 13:11 UTC, sergeyWh1te commented on ethereum-steth-v2/src/services/steth_operation/StethOperation.srv.ts
> +  public async handleInvariants(blockNumber: number): Promise<Finding[]> {
Spoke in Zoom. Decided to leave as is

2024-01-26 13:14 UTC, arwer13 approved these changes

2024-01-28 20:35 UTC, TheDZhon requested changes
Getting closer than ever before :+1: 

Please consider implementing the suggested changes for the sake of further perfection :grin:

2024-01-28 20:35 UTC, TheDZhon commented on ethereum-steth-v2/src/services/steth_operation/StethOperation.spec.ts
> +        description: `Current staking limit is 9.00 ETH this is lower than 10% of max staking limit 100.00 ETH`,
```suggestion
        description: `Current staking limit is lower than 10% of max staking limit`,
```

2024-01-28 20:35 UTC, TheDZhon commented on ethereum-steth-v2/src/services/steth_operation/StethOperation.spec.ts
> +    test('⚠️ Staking limit below 30%', async () => {
```suggestion
    test('📉 Staking limit below 30%', async () => {
```

2024-01-28 20:35 UTC, TheDZhon commented on ethereum-steth-v2/src/services/steth_operation/StethOperation.srv.ts
> +              name: `🚨 Share rate unexpected has changed`,
```suggestion
              name: `🚨🚨🚨 Share rate unexpected has changed`,
```

2024-01-28 20:35 UTC, TheDZhon commented on ethereum-steth-v2/src/services/vault/Vault.srv.ts
> +      }
looks like a duplicated piece of code, shall we extract it to a separate function?

2024-01-28 20:35 UTC, TheDZhon commented on ethereum-steth-v2/src/services/vault/Vault.srv.ts
> +          }),
maybe also avoid duplicate code

2024-01-28 20:35 UTC, TheDZhon commented on ethereum-steth-v2/src/utils/events/lido_events.ts
> +      name: '⚠️ Lido: Token rebased',
```suggestion
      name: 'ℹ️ Lido: Token rebased',
```

2024-01-28 20:35 UTC, TheDZhon commented on ethereum-steth/src/subagents/gate-seal/agent-gate-seal.ts
> +        name: "ℹ️ GateSeal: is expired",
```suggestion
        name: "ℹ️ GateSeal: a new instance created",
```

2024-01-28 20:35 UTC, TheDZhon commented on ethereum-steth-v2/README.md
> +         2. ⚠️Deposit Security: Deposits resumed
```suggestion
         2. ⚠️ Deposit Security: Deposits resumed
```

2024-01-28 20:35 UTC, TheDZhon commented on ethereum-steth-v2/README.md
> +         9. ⚠️Lido: Contract version set
```suggestion
         8. ⚠️ Lido: Funds recovered to vault
         9. ⚠️ Lido: Contract version set
```

2024-01-28 20:35 UTC, TheDZhon commented on ethereum-steth-v2/README.md
> +         10. ⚠️ Lido: Token rebased
```suggestion
         10. ℹ️ Lido: Token rebased
```

2024-01-28 20:35 UTC, TheDZhon commented on ethereum-steth-v2/README.md
> +         11. 🚨 Share rate unexpected has changed
```suggestion
         11. 🚨🚨🚨 Share rate abnormally has changed
```

2024-01-28 20:35 UTC, TheDZhon commented on ethereum-steth-v2/README.md
> +         11. 🚨 Share rate unexpected has changed
and maybe arrange items based on severity (more severe come first)

2024-01-28 20:35 UTC, TheDZhon commented on ethereum-steth-v2/README.md
> +      2. ⚠️Withdrawals: BUNKER MODE OFF! ✅
```suggestion
      2. ⚠️ Withdrawals: BUNKER MODE OFF! ✅
```

2024-01-28 20:35 UTC, TheDZhon commented on ethereum-steth-v2/README.md
> +      6. ⚠️Withdrawals: contract was unpaused
```suggestion
      5. ⚠️ Withdrawals: claimed amount is more than requested
      6. ⚠️ Withdrawals: contract was unpaused
```

2024-01-28 20:35 UTC, TheDZhon commented on ethereum-steth-v2/README.md
> +2. Withdrawals.
```suggestion
2. Withdrawals
```

2024-01-28 20:35 UTC, TheDZhon commented on ethereum-steth-v2/README.md
> +# Lido ethereum Steth bot
```suggestion
# Lido Ethereum StETH bot
```

2024-01-28 20:35 UTC, TheDZhon commented on ethereum-steth-v2/README.md
> +      2. ℹ️ GateSeal: is expired
maybe this one is about a new instance being deployed?

2024-01-29 09:17 UTC, sergeyWh1te commented on ethereum-steth-v2/src/services/steth_operation/StethOperation.spec.ts
> +        description: `Current staking limit is 9.00 ETH this is lower than 10% of max staking limit 100.00 ETH`,
done

2024-01-29 09:18 UTC, sergeyWh1te commented on ethereum-steth-v2/src/services/steth_operation/StethOperation.spec.ts
> +    test('⚠️ Staking limit below 30%', async () => {
done

2024-01-29 09:19 UTC, sergeyWh1te commented on ethereum-steth-v2/src/services/steth_operation/StethOperation.srv.ts
> +              name: `🚨 Share rate unexpected has changed`,
done

2024-01-29 09:25 UTC, sergeyWh1te commented on ethereum-steth-v2/src/services/vault/Vault.srv.ts
> +      }
changed names to:
      3. 🚨🚨🚨 Withdrawal Vault balance mismatch. [without oracle report]
      4. 🚨🚨🚨 Withdrawal Vault balance mismatch. [within oracle report]

2024-01-29 09:27 UTC, sergeyWh1te commented on ethereum-steth-v2/src/services/vault/Vault.srv.ts
> +          }),
5. 🚨🚨🚨 EL Vault balance mismatch. [without oracle report]
      6. 🚨🚨🚨 EL Vault balance mismatch. [within oracle report]

2024-01-29 09:28 UTC, sergeyWh1te commented on ethereum-steth-v2/src/utils/events/lido_events.ts
> +      name: '⚠️ Lido: Token rebased',
done

2024-01-29 09:30 UTC, sergeyWh1te commented on ethereum-steth-v2/README.md
> +         2. ⚠️Deposit Security: Deposits resumed
done

2024-01-29 09:31 UTC, sergeyWh1te commented on ethereum-steth-v2/README.md
> +         9. ⚠️Lido: Contract version set
done

2024-01-29 09:32 UTC, sergeyWh1te commented on ethereum-steth-v2/README.md
> +         10. ⚠️ Lido: Token rebased
done

2024-01-29 09:33 UTC, sergeyWh1te commented on ethereum-steth-v2/README.md
> +      2. ⚠️Withdrawals: BUNKER MODE OFF! ✅
done

2024-01-29 09:33 UTC, sergeyWh1te commented on ethereum-steth-v2/README.md
> +      6. ⚠️Withdrawals: contract was unpaused
done

2024-01-29 09:33 UTC, sergeyWh1te commented on ethereum-steth-v2/README.md
> +2. Withdrawals.
done

2024-01-29 09:34 UTC, sergeyWh1te commented on ethereum-steth-v2/README.md
> +# Lido ethereum Steth bot
done

2024-01-29 09:39 UTC, sergeyWh1te commented on ethereum-steth-v2/README.md
> +      2. ℹ️ GateSeal: is expired
Changed to: `🚨️ GateSeal: is expired. Update code!`

2024-01-29 11:33 UTC, TheDZhon approved these changes
LGTM

2024-01-29 12:27 UTC, vgorkavenko submitted a review, later dismissed

2024-01-29 12:47 UTC, arwer13 submitted a review, later dismissed

2024-01-29 13:06 UTC, bulbozaur approved these changes
LGTM

2024-01-29 13:23 UTC, arwer13 approved these changes

2024-01-29 13:24 UTC, vgorkavenko approved these changes

2024-01-29 13:25 UTC, merged