Eth steth set original rpc url
lidofinance/alerting-forta pull request #474
Opened 2024-02-05 12:13 UTC by sergeyWh1te

Added: 
- Health check mechanism
- Wrappers for network and db findings
-  Removed from finding's description, Ts error object.
- Refactored **WithdrawalsSrv** from using Map for withdrawal_requests queue to sqlite table
- Tests for GateSealSrv
- Split up IETHprovider to IGateSealClient, IStethClient, IVaultClient, IWithdrawalsClient 

**Made audit for severity levels and their pictures**

2024-02-05 16:38 UTC, TheDZhon requested changes
:+1: Utterly cool, thank you so much!

I'd suggest tuning up some severities still before merging this one.

2024-02-05 16:38 UTC, TheDZhon commented on ethereum-steth/src/services/withdrawals/Withdrawals.srv.ts
> +          Drained stake limit: ${drainedStakeLimit.div(ETH_DECIMALS).toFixed(2)} stETH`,
```suggestion
          Spent stake limit: ${spentStakeLimit.div(ETH_DECIMALS).toFixed(2)} stETH`,
```

2024-02-05 16:38 UTC, TheDZhon commented on ethereum-steth/src/services/withdrawals/Withdrawals.srv.ts
>            name: `⚠️ Withdrawals: ${drainedStakeLimitRate.times(
```suggestion
          name: `⚠️ Withdrawals: ${spentStakeLimitRate.times(
```

2024-02-05 16:38 UTC, TheDZhon commented on ethereum-steth/src/services/withdrawals/Withdrawals.srv.ts
>              name: `⚠️ Withdrawals: ${unclaimedSizeRate.times(100).toFixed(2)}% of finalized requests are unclaimed`,
Let's change: :warning:  → :information_source:

2024-02-05 16:38 UTC, TheDZhon commented on ethereum-steth/src/services/withdrawals/Withdrawals.srv.ts
> +            severity: FindingSeverity.Medium,
I would suggest leaving 'info'

2024-02-05 16:38 UTC, TheDZhon commented on ethereum-steth/src/services/withdrawals/Withdrawals.srv.ts
>              name: `⚠️ Withdrawals: unclaimed requests size is more than withdrawal queue balance`,
⚠️ ⇒ 🚨🚨🚨

It's critical and would need to activate GateSeal most likely

2024-02-05 16:38 UTC, TheDZhon commented on ethereum-steth/src/services/withdrawals/Withdrawals.srv.ts
> -            severity: FindingSeverity.Critical,
Should be critical

2024-02-05 16:38 UTC, TheDZhon commented on ethereum-steth/src/services/withdrawals/Withdrawals.srv.ts
> +              name: `⚠️ Withdrawals: claimed amount is more than requested`,
🚨🚨🚨

Should be critical (invariant violation)

2024-02-05 16:38 UTC, TheDZhon commented on ethereum-steth/src/services/withdrawals/Withdrawals.srv.ts
> +              severity: FindingSeverity.Medium,
should be critical

2024-02-06 10:19 UTC, sergeyWh1te commented on ethereum-steth/src/services/withdrawals/Withdrawals.srv.ts
> +          Drained stake limit: ${drainedStakeLimit.div(ETH_DECIMALS).toFixed(2)} stETH`,
done

2024-02-06 10:19 UTC, sergeyWh1te commented on ethereum-steth/src/services/withdrawals/Withdrawals.srv.ts
>            name: `⚠️ Withdrawals: ${drainedStakeLimitRate.times(
done

2024-02-06 10:21 UTC, sergeyWh1te commented on ethereum-steth/src/services/withdrawals/Withdrawals.srv.ts
>              name: `⚠️ Withdrawals: ${unclaimedSizeRate.times(100).toFixed(2)}% of finalized requests are unclaimed`,
done

2024-02-06 10:21 UTC, sergeyWh1te commented on ethereum-steth/src/services/withdrawals/Withdrawals.srv.ts
> +            severity: FindingSeverity.Medium,
done

2024-02-06 10:23 UTC, sergeyWh1te commented on ethereum-steth/src/services/withdrawals/Withdrawals.srv.ts
>              name: `⚠️ Withdrawals: unclaimed requests size is more than withdrawal queue balance`,
done

2024-02-06 10:24 UTC, sergeyWh1te commented on ethereum-steth/src/services/withdrawals/Withdrawals.srv.ts
> -            severity: FindingSeverity.Critical,
done

2024-02-06 10:25 UTC, sergeyWh1te commented on ethereum-steth/src/services/withdrawals/Withdrawals.srv.ts
> +              name: `⚠️ Withdrawals: claimed amount is more than requested`,
done

2024-02-06 10:25 UTC, sergeyWh1te commented on ethereum-steth/src/services/withdrawals/Withdrawals.srv.ts
> +              severity: FindingSeverity.Medium,
done

2024-02-06 11:33 UTC, TheDZhon approved these changes
:+1:

2024-02-06 11:58 UTC, merged