feature: forta local development capability
lidofinance/alerting-forta pull request #492
Opened 2024-03-11 15:05 UTC by sergeyWh1te

# Added:

* Forta-local mode

2024-03-11 19:23 UTC, TheDZhon requested changes
Thank you for spearheading the effort!

2024-03-11 19:23 UTC, TheDZhon commented on README.md
> +- [Forta-scanner](https://github.com/forta-network/forta-node/blob/master/cmd/node/nodecmd/nodecmd.go#L40) service communicating with forta-agent via gRPC
```suggestion
- [NATS](https://nats.io/) — Message bus 
- [Forta-node](https://github.com/forta-network/forta-node/blob/master/cmd/node/nodecmd/nodecmd.go#L64) — Forta wrapper over the Ethereum-like node
- [Forta-scanner](https://github.com/forta-network/forta-node/blob/master/cmd/node/nodecmd/nodecmd.go#L40) — service communicating with forta-agent via gRPC
```

2024-03-11 19:23 UTC, TheDZhon commented on README.md
> +2. Clone forta-node repo to somewhere. `git clone https://github.com/forta-network/forta-node`
```suggestion
2. Clone forta-node repo: `git clone https://github.com/forta-network/forta-node`
```

2024-03-11 19:23 UTC, TheDZhon commented on README.md
> +3. `cd forta-node && make containers`. It creates containers for local using
```suggestion
3. `cd forta-node && make containers`. It creates containers for local usage
```

2024-03-11 19:23 UTC, TheDZhon commented on README.md
> +Also, it's usefully for understanding `forta-scanner` config file - check https://github.com/forta-network/forta-node/blob/master/config/config.go#L155
```suggestion
Also, the `forta-scanner` config file is useful for a deep dive — check the following: https://github.com/forta-network/forta-node/blob/master/config/config.go#L155
```

2024-03-11 19:23 UTC, TheDZhon commented on README.md
> +Just move to bot directory and run `yarn start`. [Forta-sdk](https://github.com/forta-network/forta-bot-sdk/tree/master/sdk) provides emulation prod environment for simplifier local development
```suggestion
Just navigate to the bot directory and run `yarn start`. [Forta-sdk](https://github.com/forta-network/forta-bot-sdk/tree/master/sdk) provides emulation prod environment for a simplified local development
```

2024-03-11 19:23 UTC, TheDZhon commented on forta-local-config.yml
> +  privateKeyHex: 984d28fde238c32d06420db29b7277f5fd24c61954d2da491bf7d1ef19996bd0
is it safe to place here?

2024-03-12 07:13 UTC, sergeyWh1te commented on forta-local-config.yml
> +  privateKeyHex: 984d28fde238c32d06420db29b7277f5fd24c61954d2da491bf7d1ef19996bd0
Yes. For local goals(our setup) - unfortunately it's only unused required parameter for forta-scanner.

2024-03-12 09:12 UTC, TheDZhon approved these changes
![Uploading image.png…]()

2024-03-12 10:48 UTC, merged