Feat/l2 bridge scroll (separated to simplify review)
lidofinance/alerting-forta pull request #504
Opened 2024-03-29 12:46 UTC by arwer13

2024-03-29 13:28 UTC, sergeyWh1te requested changes
Need to insert line to github/.codeowners with scroll

2024-03-29 13:28 UTC, sergeyWh1te commented on l2-bridge-scroll/src/utils/constants.ts
> +// NB: obfuscate url if the rpc isn't public Buffer.from('???', 'base64').toString('utf-8')
let's remove this comment

also, we use constants only in one place. They could'be unshared
Or add them into one exportable value - Address

2024-03-29 13:28 UTC, sergeyWh1te commented on l2-bridge-scroll/tests/e2e/scroll_provider.spec.ts
> -    const blocks = await app.mantleClient.fetchBlocks(start, end)
This test could be pass becasue latest scroll block at current moment - 4_497_161

2024-04-03 13:09 UTC, arwer13 commented on l2-bridge-scroll/tests/e2e/scroll_provider.spec.ts
> -    const blocks = await app.mantleClient.fetchBlocks(start, end)
thanks, fixed

2024-04-03 13:14 UTC, arwer13 commented
Merging to the main feature branch, because this PR was auxiliary.

2024-04-03 13:14 UTC, merged