Add `csm-alerts` bot
lidofinance/alerting-forta pull request #584
Opened 2024-07-19 21:09 UTC by larmork

2024-07-23 17:57 UTC, madlabman requested changes

2024-07-23 17:57 UTC, madlabman commented on csm-alerts/src/utils/events/cs_fee_oracle_events.ts
> +    },
You have to track the list of hashes for the given slot and alert only if more than to distinct hashes for the same slot are observed.

2024-07-23 17:57 UTC, madlabman commented on csm-alerts/README.md
> +      4. 🔴 HIGH: BondCurveSet(uint256 indexed nodeOperatorId, uint256 curveId)
+ STETH approval?

2024-07-23 17:57 UTC, madlabman commented on csm-alerts/README.md
> +      8. 🔵 INFO: ReportSettled(uint256 indexed refSlot, uint256 distributed, bytes32 treeRoot, string treeCid)
+ HIGH: report overdue (expect consensus every 28 days)

2024-07-23 17:57 UTC, madlabman commented on csm-alerts/README.md
> +      2. 🔵 INFO: DistributionDataUpdated -> Oracle settled a new report.
+ No fees distributed for X days (repeat every 1 day).

2024-07-23 17:57 UTC, madlabman commented on csm-alerts/src/utils/events/cs_accounting_events.ts
> +      description: (args: Result) => `Bond curve updated with curve ID ${args.curveId}. Bond curve: ${args.bondCurve}`,
`bondCurve` values can be run through the `toEthString` helper.

2024-07-23 17:57 UTC, madlabman commented on csm-alerts/src/services/CSFeeOracle/CSFeeOracle.srv.spec.ts
> +      expect(results[0].getAlertid()).toEqual(expected[0].alertId)
Is there a way to make it work with jest snapshots?

2024-07-23 19:04 UTC, larmork commented on csm-alerts/src/main.ts
> +  const address: AddressHol = Address
Should I make like a `constants.mainnet.ts` file and switch between `constants.mainnet.ts` and `constants.holesky.ts` depending on config chain ID?

2024-07-23 19:12 UTC, larmork commented on csm-alerts/src/main.ts
> +  // const etherscanProvider = new ethers.providers.EtherscanProvider(holeskyNetwork, config.etherscanKey)
Not in use. To be deleted

2024-07-23 19:15 UTC, larmork commented on csm-alerts/src/main.ts
> +    getPausableEvents(),
Good point actually, I'll implement it soon

2024-07-23 19:25 UTC, larmork commented on csm-alerts/src/utils/events/pausable_events.ts
> +      name: `🟣 ${proxyInfo.name}: contract was resumed`,
Not a huge fan of those symbols, prefer using colours as in Forta for severity types. But if it's how it should be for all bots, I'll fix that. Also, if it's important, should I change symbols for `HIGH`, `MEDIUM`, etc. severity types as well?

2024-07-23 19:27 UTC, larmork commented on csm-alerts/src/utils/constants.holesky.ts
> +export const LIDO_PROXY_CONTRACTS: LidoProxy[] = [
I'll change naming here, thanks

2024-07-23 19:32 UTC, larmork commented on csm-alerts/src/utils/constants.holesky.ts
> +  GATE_SEAL_ADDRESS: string
Right, will rename this one

2024-07-23 19:47 UTC, larmork commented on csm-alerts/src/utils/constants.holesky.ts
> +export type AddressHol = {
```
export const DeploymentAddresses: Address = {
```

So it will be like this for the constants. As for unused addresses, I'll surely delete them

2024-07-23 20:02 UTC, larmork commented on csm-alerts/Dockerfile
> +RUN apk add --no-cache python3=3.11.8-r0 g++=12.2.1_git20220924-r10 make=4.4.1-r1 sqlite=3.41.2-r3
I'll remove it for now

2024-07-23 20:06 UTC, larmork commented on csm-alerts/src/utils/env/env.ts
> +    // this.useFortaProvider = JSON.parse(process.env.USE_FORTA_RPC_URL!)
It is. To be removed

2024-07-23 20:20 UTC, larmork commented on csm-alerts/src/utils/events/cs_accounting_events.ts
> +      description: (args: Result) => `Bond curve updated with curve ID ${args.curveId}. Bond curve: ${args.bondCurve}`,
Sure, I'll use it here, thanks

2024-07-23 20:24 UTC, larmork commented on csm-alerts/src/utils/events/cs_accounting_events.ts
> +      abi: 'event ChargeRecipientSet(address chargeRecipient)',
Got it, will be fixed!

2024-07-23 20:55 UTC, larmork commented on csm-alerts/src/utils/events/pausable_events.ts
> +  const eventsDesc: EventOfNotice[] = [
```
  export function getPausableEvents(): EventOfNotice[] {
    return CSM_PROXY_CONTRACTS.flatMap((proxyInfo: Proxy) => {
```

Yeah, that's more appealing

2024-07-23 21:19 UTC, larmork commented on csm-alerts/src/utils/events/pausable_events.ts
> +const PAUSABLE_EVENTS: EventOfNotice[] = LIDO_PROXY_CONTRACTS.map((proxyInfo: LidoProxy) => {
All of `CSM_PROXY_CONTRACTS` except `CSFeeDistributor`. What if I'll filter `CSM_PROXY_CONTRACTS` here?

```
proxyInfo.name !== 'CSFeeDistributor'
```

2024-07-23 21:25 UTC, larmork commented on csm-alerts/src/handlers/tx.handler.ts
> +      const csFeeDistributorFindings = await this.csFeeDistributorSrv.handleTransaction(txEvent)
Yep, will get fixed

2024-07-23 21:33 UTC, larmork commented on csm-alerts/src/clients/eth_provider.ts
> +  ): Promise<E.Either<Error, TransactionResponse[]>> {
Potentially, but not rn. Do you think it should be removed for now?

2024-07-23 21:36 UTC, larmork commented on csm-alerts/.dockerignore
> +forta.config.json
Got it

2024-07-23 21:39 UTC, larmork commented on csm-alerts/src/generated/proto/.gitignore
> +*.js
Will mention directory in the outer `.gitignore`

2024-07-23 21:41 UTC, larmork commented on csm-alerts/Dockerfile
> +FROM base as builder
I'll try to figure out what the problem is here

2024-07-23 21:43 UTC, larmork commented on csm-alerts/alerts.yml
> +        expr: increase(csm_network_errors_total[15m]) >= 25
Fair enough, I'll rename it

2024-07-23 21:48 UTC, larmork commented on csm-alerts/src/utils/events/burner_events.ts
> +export function getBurnerEvents(BURNER_ADDRESS: string): EventOfNotice[] {
Then I'll suggest to use here implementation similar to that we have in `pausable_events.ts` with mapping contracts from `CSM_PROXY_CONTRACTS`

2024-07-23 22:06 UTC, larmork commented on csm-alerts/src/utils/events/burner_events.ts
> +      abi: 'event ERC20Recovered(address indexed requestedBy, address indexed token,uint256 amount)',
Checked and fixed!

2024-07-23 22:07 UTC, larmork commented on csm-alerts/src/utils/events/burner_events.ts
> +      name: '🔴 Lido Burner: ERC20 recovered',
Should be `AssetRecoverer` instead

2024-07-23 22:30 UTC, larmork commented on csm-alerts/src/utils/events/cs_fee_distributor_events.ts
> +        `Oracle settled a new report for slot ${args.refSlot}. Report hash: ${args.reportHash}, Distributed amount: ${args.distributed}`,
Replaced with correct description

2024-07-23 22:33 UTC, larmork commented on csm-alerts/src/utils/events/cs_fee_distributor_events.ts
> +      abi: 'event DistributionDataUpdated(uint256 indexed refSlot, bytes32 reportHash, uint256 distributed)',
Replaced with the correct one `event DistributionDataUpdated(uint256 totalClaimableShares, bytes32 treeRoot, string treeCid)`

2024-07-23 22:35 UTC, larmork commented on csm-alerts/src/utils/events/cs_fee_distributor_events.ts
> +        return null
Checking in `handleEventsOfNotice()`: 


```
from === DeploymentAddresses.CS_FEE_DISTRIBUTOR_ADDRESS.toLowerCase() &&
to !== DeploymentAddresses.CS_ACCOUNTING_ADDRESS.toLowerCase()
```

2024-07-24 06:55 UTC, larmork commented on csm-alerts/src/services/CSFeeOracle/CSFeeOracle.srv.spec.ts
> +      expect(results[0].getAlertid()).toEqual(expected[0].alertId)
So like this, I think
```
expect(results).toMatchSnapshot()
```

2024-07-31 07:25 UTC, madlabman commented on csm-alerts/src/main.ts
> +  const address: AddressHol = Address
Yes

2024-07-31 07:29 UTC, madlabman commented on csm-alerts/src/utils/events/pausable_events.ts
> +      name: `🟣 ${proxyInfo.name}: contract was resumed`,
I think for HIGH and MEDIUM the symbols are fine. Just 🟣 is hard to match with critical severity at the first glance.

2024-07-31 07:48 UTC, madlabman commented on csm-alerts/src/utils/constants.holesky.ts
> +  ACCOUNTING_HASH_CONSENSUS_ADDRESS: string
This one is redundant, and the below one should be more specific.

2024-07-31 07:48 UTC, madlabman commented on csm-alerts/src/utils/constants.holesky.ts
> +export type Address = {
Still `Address`, which is ambiguous.

2024-07-31 07:48 UTC, madlabman commented on csm-alerts/src/utils/events/pausable_events.ts
> +  return CSM_PROXY_CONTRACTS.filter((proxyInfo: Proxy) => proxyInfo.name !== 'CSFeeDistributor').flatMap(
Just make a separate constant with pausable contracts.

2024-07-31 07:48 UTC, madlabman commented on csm-alerts/src/utils/events/pausable_events.ts
> +const PAUSABLE_EVENTS: EventOfNotice[] = LIDO_PROXY_CONTRACTS.map((proxyInfo: LidoProxy) => {
Pausable contracts have nothing to do with proxies, just add a new constant.

2024-07-31 07:48 UTC, madlabman commented on csm-alerts/src/services/CSFeeDistributor/CSFeeDistributor.srv.ts
> +
Consider adding 
```
    const currBlock = await this.csAccountingClient.getBlockByNumber(currentBlock)
    if (E.isLeft(currBlock)) {
      this.logger.error(elapsedTime(`Failed [${this.name}.initialize]`, start))
      return currBlock.left
    }
```
as in other services.

2024-07-31 07:48 UTC, madlabman commented on csm-alerts/src/clients/eth_provider.ts
> +  ): Promise<E.Either<Error, TransactionResponse[]>> {
As far as I undestrand, the version of `ethers` we're currently using doesn't support `holesky` network for the Etherscan provider. At the same time, a newer version doesn't implement `getHistory` method for this provider. It would be nice if you check it.

2024-07-31 10:03 UTC, madlabman commented on csm-alerts/src/services/CSFeeOracle/CSFeeOracle.srv.ts
> +    )
I think here we can use the same approach as for `lastDistributionDataUpdated`: to fetch the frame-ago events during the initialization and then update on the corresponding event.

2024-07-31 10:03 UTC, madlabman commented on csm-alerts/src/services/CSFeeOracle/CSFeeOracle.srv.ts
> +    if (reportDelayUpdated > ONE_MONTH) {
And do not forget about stop condition, otherwise it will fire for every block.

2024-07-31 10:03 UTC, madlabman commented on csm-alerts/src/utils/events/cs_accounting_events.ts
> +      description: (args: Result) => `Bond curve updated with curve ID ${args.curveId}. Bond curve: ${args.bondCurve}`,
`bondCurve` is an array, use `map` instead.

2024-07-31 11:14 UTC, larmork commented on csm-alerts/src/utils/constants.holesky.ts
> +  ACCOUNTING_HASH_CONSENSUS_ADDRESS: string
Do you think `CS_FEE_ORACLE_HASH_CONSENSUS_ADDRESS` might be better? Instead of `HASH_CONSENSUS_ADDRESS`

2024-08-19 09:19 UTC, madlabman commented on csm-alerts/src/services/CSFeeDistributor/CSFeeDistributor.srv.ts
> +        event.args.to !== this.csAccountingAddress.toLowerCase()
It's safer to convert the both sides to lowercase.

2024-08-19 09:19 UTC, madlabman commented on csm-alerts/src/services/CSFeeOracle/CSFeeOracle.srv.ts
> +    const reportReceivedStartBlock = currentBlock - Math.ceil(ONE_MONTH / SECONDS_PER_SLOT)
Use an actual frame instead of `ONE_MONTH`.

2024-08-19 09:19 UTC, madlabman commented on csm-alerts/src/services/CSFeeOracle/CSFeeOracle.srv.ts
> +    const reportDelay = now - (this.lastReportSubmitTimestamp ? this.lastReportSubmitTimestamp : 0)
The very first report case isn't handled. At startup, we will get false alert and will continue to receive them every day. I think we can simply return if `epoch = frameConfig.initialEpoch + frameConfig.epochsPerFrame` hasn't been reached yet.

2024-08-19 09:19 UTC, madlabman commented on csm-alerts/src/services/CSFeeOracle/CSFeeOracle.srv.ts
> +      })
You store member's report only if it's an alternative one. Move it outside if statement.

2024-08-19 09:19 UTC, madlabman commented on csm-alerts/src/services/CSFeeOracle/CSFeeOracle.srv.ts
> +    const reportEvent = filterLog(txEvent.logs, HASH_CONSENSUS_REPORT_RECEIVED_EVENT, this.hashConsensusAddress)
Look for
```solidity
event ReportSubmitted(
    uint256 indexed refSlot,
    bytes32 hash,
    uint256 processingDeadlineTime
);
```
on the Oracle.

2024-08-20 08:25 UTC, madlabman commented on csm-alerts/src/services/CSFeeOracle/CSFeeOracle.srv.ts
> +    const currentEpoch = Math.floor(now / (frameConfig.epochsPerFrame * 32 * SECONDS_PER_SLOT))
It should be `(now - genesisTimestamp) // 12 // 32)`, see e.g. [here](https://github.com/lidofinance/community-staking-module/blob/4ea96e1161b963d0911df90630dec5cb2080bbfa/src/lib/base-oracle/HashConsensus.sol#L809-L813)

2024-08-20 08:25 UTC, madlabman commented on csm-alerts/src/services/CSFeeDistributor/CSFeeDistributor.srv.ts
> +      currentBlock,
Why last block only?

2024-08-20 08:25 UTC, madlabman commented on csm-alerts/src/services/CSFeeDistributor/CSFeeDistributor.srv.ts
> +    if (timeSinceLastAlert > ONE_DAY) {
No report yet situation isn't handled. Make sense to do similar to CSFeeOracle.srv

2024-08-20 08:25 UTC, madlabman commented on csm-alerts/src/services/CSFeeDistributor/CSFeeDistributor.srv.ts
> +    if (timeSinceLastAlert > ONE_DAY) {
Why it's not moved from tx handler?

2024-08-20 09:29 UTC, larmork commented on csm-alerts/src/services/CSFeeDistributor/CSFeeDistributor.srv.ts
> +    if (timeSinceLastAlert > ONE_DAY) {
You mean skip checks if we are within initial epochs?

2024-09-01 17:38 UTC, merged