feat: new CCC events added
lidofinance/alerting-forta pull request #590
Opened 2024-08-07 14:23 UTC by Ivan-Feofanov

2024-08-07 14:51 UTC, BATMAH69 submitted a review, later dismissed

2024-08-08 12:45 UTC, tamtamchik commented on l2-bridge-ethereum/src/constants.ts
> +    name: "L1 Cross-chain controller: Message sent",
Add proper icon?

2024-08-08 12:45 UTC, BATMAH69 submitted a review, later dismissed

2024-08-08 12:48 UTC, tamtamchik commented on l2-bridge-ethereum/src/constants.ts
> +    name: "L1 Cross-chain controller: Message sent",
ℹ️ BNB a.DI: Message sent by the X adapter

2024-08-08 12:55 UTC, tamtamchik commented
It looks like we deprecate this bot, and you need to fork it and deploy it under your supervision with all the checks that DAO team needs from this bot

2024-08-08 12:56 UTC, tamtamchik requested changes
It looks like we deprecate this bot, and you need to fork it and deploy it under your supervision with all the checks that the DAO team needs from this bot.

2024-08-08 13:16 UTC, tamtamchik approved these changes

2024-08-08 13:18 UTC, merged

2024-08-08 13:18 UTC, tamtamchik commented
Disclaimer: approved for easier code transfer to the Dao bot, this code should not be deployed as is.