CSM alerts
lidofinance/alerting-forta pull request #621
Opened 2024-10-09 14:20 UTC by madlabman

2024-10-21 11:43 UTC, vgorkavenko submitted a review, later dismissed

2024-10-23 07:14 UTC, dgusakov requested changes
Pls check readme for consistency with the code + check alert emoji so that they match severities

2024-10-23 07:14 UTC, dgusakov commented on csm-alerts/src/services/CSAccounting/CSAccounting.srv.ts
> +                    description: `There's a valuable amount of shares to recover on CSAccounting.`,
Add amount pls

2024-10-23 07:14 UTC, dgusakov commented on csm-alerts/src/services/CSModule/CSModule.srv.ts
> +                    name: `🟢 CSModule: Too many empty batches in the deposit queue.`,
Green marks for the low-severity alerts seem a bit confusing

2024-10-23 07:14 UTC, dgusakov commented on csm-alerts/src/services/CSModule/CSModule.srv.ts
> +                    name: '🟢 CSModule: Too many validators in the queue.',
```suggestion
                    name: '🟢 CSModule: Significant number of validator keys in the queue.',
```

2024-10-23 07:14 UTC, dgusakov commented on csm-alerts/src/services/EventsWatcher/events/assetRecoverer.ts
> +                name: '🔴 AssetRecoverer: StETH Shares recovered',
```suggestion
                name: '🔴 AssetRecoverer: stETH Shares recovered',
```

2024-10-23 07:14 UTC, dgusakov commented on csm-alerts/src/services/EventsWatcher/events/hashconsensus.ts
> +            name: '🔵 CSM HashConsensus: Consensus reached, report received',
```suggestion
            name: '🔵 CSM HashConsensus: Consensus reached',
```

2024-10-23 07:14 UTC, dgusakov commented on csm-alerts/src/services/EventsWatcher/events/module.ts
> +            description: () => 'CSM public release is activated! 🥳',
```suggestion
            description: () => 'CSM public release has been activated! 🥳',
```

2024-10-23 07:14 UTC, dgusakov commented on csm-alerts/src/services/EventsWatcher/events/module.ts
> +            severity: FindingSeverity.High,
```suggestion
            severity: FindingSeverity.Info,
```

2024-10-23 07:14 UTC, dgusakov commented on csm-alerts/src/services/EventsWatcher/events/module.ts
> +            severity: FindingSeverity.High,
```suggestion
            severity: FindingSeverity.Info,
```

2024-10-23 07:14 UTC, dgusakov commented on csm-alerts/src/services/EventsWatcher/events/module.ts
> +            severity: FindingSeverity.High,
```suggestion
            severity: FindingSeverity.Info,
```

2024-10-23 07:14 UTC, dgusakov commented on csm-alerts/src/services/EventsWatcher/events/module.ts
> +            severity: FindingSeverity.High,
```suggestion
            severity: FindingSeverity.Info,
```

2024-10-23 07:14 UTC, dgusakov commented on csm-alerts/src/services/EventsWatcher/events/oracle.ts
> +            name: '🔵 CSFeeOracle: Processing missed',
```suggestion
            name: '🔴 CSFeeOracle: Processing missed',
```

2025-02-03 14:26 UTC, dgusakov approved these changes

2025-02-03 14:26 UTC, merged